// Phase 4 DARK: does the illustration set (art/**, 38 SVGs, generated by scripts/make-art.mjs) have a dark form?
// Each SVG is rasterised in WebKit at 2x its viewBox and composited over the Midnight card (--surface #241E19) and
// the Hearth card (#FFFCF8). Reported per file: painted share (alpha > 0.5), mean relative luminance of the painted
// pixels, the share of painted pixels brighter than L 0.45 ("pale"), the share of the whole box that is an opaque
// backdrop (a panel), and the contrast of the mean composited colour against each surface.
// Also greps the files for currentColor / prefers-color-scheme / CSS variables (a way to adapt).
//   node audits/tools/phase4/DARK/art-dark.mjs  -> audits/evidence/p4/DARK/art-dark.json + art-dark-sheet.png
import fs from 'node:fs'; import path from 'node:path';
import { playwright, ROOT } from '../../lib/local.mjs';
const ART = path.join(ROOT, 'art');
const files = fs.readdirSync(ART).filter(d => fs.statSync(path.join(ART, d)).isDirectory()).flatMap(d => fs.readdirSync(path.join(ART, d)).filter(f => f.endsWith('.svg')).map(f => `${d}/${f}`));
const pw = playwright(); const browser = await pw.webkit.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1200, height: 900 } });
await page.setContent('<html><body style="margin:0;background:#241E19"></body></html>');
const out = { note: 'See header of audits/tools/phase4/DARK/art-dark.mjs. surfaces: midnight #241E19, hearth #FFFCF8.', files: [] };
for (const f of files) {
  const src = fs.readFileSync(path.join(ART, f), 'utf8');
  const adapt = { currentColor: (src.match(/currentColor/g) || []).length, prefersColorScheme: (src.match(/prefers-color-scheme/g) || []).length, cssVar: (src.match(/var\(--/g) || []).length };
  const b64 = Buffer.from(src).toString('base64');
  const s = await page.evaluate(async b64 => {
    const img = new Image(); img.src = 'data:image/svg+xml;base64,' + b64; await img.decode();
    const w = Math.min(800, (img.naturalWidth || 300) * 2), h = Math.round(w * (img.naturalHeight || 200) / (img.naturalWidth || 300));
    const c = document.createElement('canvas'); c.width = w; c.height = h; const g = c.getContext('2d'); g.drawImage(img, 0, 0, w, h);
    const d = g.getImageData(0, 0, w, h).data;
    const lin = v => { v /= 255; return v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4; };
    const L = (r, gg, b) => 0.2126 * lin(r) + 0.7152 * lin(gg) + 0.0722 * lin(b);
    let painted = 0, opaque = 0, sumL = 0, pale = 0, n = w * h; const comp = { m: [0, 0, 0], h: [0, 0, 0] };
    const M = [36, 30, 25], H = [255, 252, 248];
    for (let i = 0; i < d.length; i += 4) {
      const a = d[i + 3] / 255;
      for (let k = 0; k < 3; k++) { comp.m[k] += d[i + k] * a + M[k] * (1 - a); comp.h[k] += d[i + k] * a + H[k] * (1 - a); }
      if (a > 0.5) { painted++; const l = L(d[i], d[i + 1], d[i + 2]); sumL += l; if (l > 0.45) pale++; }
      if (a > 0.98) opaque++;
    }
    const mean = arr => arr.map(v => v / n);
    return { w, h, paintedShare: +(painted / n).toFixed(3), opaqueShare: +(opaque / n).toFixed(3), meanL: painted ? +(sumL / painted).toFixed(3) : null, paleShare: painted ? +(pale / painted).toFixed(3) : null, meanOnMidnight: mean(comp.m), meanOnHearth: mean(comp.h) };
  }, b64);
  const lin = v => { v /= 255; return v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4; };
  const Lm = c => 0.2126 * lin(c[0]) + 0.7152 * lin(c[1]) + 0.0722 * lin(c[2]);
  const CR = (a, b) => { const x = Lm(a), y = Lm(b); return +((Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05)).toFixed(2); };
  const rec = { file: f, ...adapt, ...s, meanVsMidnightSurface: CR(s.meanOnMidnight, [36, 30, 25]), meanVsHearthSurface: CR(s.meanOnHearth, [255, 252, 248]) };
  delete rec.meanOnMidnight; delete rec.meanOnHearth; out.files.push(rec);
  console.log(f.padEnd(26), 'painted', rec.paintedShare, 'opaque', rec.opaqueShare, 'meanL', rec.meanL, 'pale', rec.paleShare, 'glare vs midnight card', rec.meanVsMidnightSurface, 'vs hearth', rec.meanVsHearthSurface, 'adapt', adapt.currentColor + adapt.prefersColorScheme + adapt.cssVar);
}
// contact sheet: a sample of the art on the Midnight card at 1x
const pick = ['app/leftovers.svg', 'app/timer.svg', 'app/tally.svg', 'app/verses.svg', 'app/f260.svg', 'empty/fridge.svg', 'empty/prayers.svg', 'hero/play.svg', 'story/01-creation.svg', 'story/03-promise.svg', 'story/09-nativity.svg', 'story/05-law.svg'];
const cells = pick.map(f => `<figure style="margin:8px;display:inline-block;background:#241E19;border-radius:16px;padding:10px;width:250px;vertical-align:top"><img style="width:230px;height:auto;display:block" src="data:image/svg+xml;base64,${Buffer.from(fs.readFileSync(path.join(ART, f))).toString('base64')}"><figcaption style="color:#F3EDE5;font:12px system-ui;margin-top:6px">${f}</figcaption></figure>`).join('');
await page.setContent(`<html><body style="margin:0;padding:8px;background:#1A1512;width:1100px">${cells}</body></html>`);
await page.waitForTimeout(300);
await page.screenshot({ path: path.join(ROOT, 'audits/evidence/p4/DARK/art-dark-sheet.png'), fullPage: true });
await browser.close();
fs.writeFileSync(path.join(ROOT, 'audits/evidence/p4/DARK/art-dark.json'), JSON.stringify(out, null, 1));
