// Phase 5 fixes for the shell and platform findings (audits/02-shell.md). One entry per ID:
//   'ID': [batch, effort S|M|L, proposed fix, why it matters (only where the finding states none)]
// A pointer ID keeps its own entry and names its primary; it is closed by the primary's fix.
export default {
  // ── Home and launcher ──
  'P2-HOME-01': ['2a', 'S', 'Home re-renders only the cards whose data changed, and never replaces a focused input: skip the reminders card while #rem-in has focus or text, and keep the draft in memory across renders.'],
  'P2-HOME-02': ['0b', 'S', 'F260 writes the date into its summary (`readOn: hub.today()`), and Home, the TV, chat and the 8 pm job read "done today" only when that date is today (apps/f260.html:1506-1509; index.html:1164; worker/src/reminders.js:88-96).'],
  'P2-HOME-03': ['2a', 'S', 'After Switch, the next person lands on Home: showTab("home") when a new session starts, never the previous tab.'],
  'P2-HOME-04': ['0b', 'S', 'Pointer to P2-SYNC-15: closed by the first-load signal (Home shows skeletons until each card\'s channel has pulled once).'],
  'P2-HOME-05': ['2a', 'S', 'Render each Home card from its own channel and skip the rebuild when the pull changed nothing (compare the channel\'s `since`).'],
  'P2-HOME-06': ['2a', 'S', 'Kid Verse stops putting the kid\'s name into the activity text (apps/kidverse.html:332, 481, 640); the TV keeps its byline. A one-off cleanup is not needed: feed lines age out.'],
  'P2-HOME-07': ['2c', 'S', 'Either Kid Verse writes the week\'s kid line (`line`) into the family week row when the week is set, or the TV derives it from the week number; remove the dead read otherwise (index.html:1056).'],
  'UX-HOME-1': ['2a', 'M', 'Glance roles from the proposed tokens (`--fs-glance-1/2/3`, 44-96 px) for Home\'s key numbers on the iPad, and a calm "kitchen" layout when idle: today\'s reading, the running timer, food to eat soon.', 'The Kitchen iPad is read from across the room; today its key numbers are 2-3 mm tall.'],
  'UX-HOME-2': ['2c', 'M', 'On the TV, news lines and names use the 10-foot scale (`data-tv-scale="10ft"`, decision D16) with the re-laid-out grid.', 'The TV is read from the sofa at 3 m; its newest facts are its smallest text.'],
  'GAP-HOME-1': ['A:timer', 'M', 'A running timer shows for everyone on the Kitchen iPad and the TV (a family `timers` channel mirrored from the person\'s timer.active, read-only for others), labelled with the owner\'s face.', 'Whoever is in the kitchen needs to see a timer someone else started.'],
  'VIS-HOME-1': ['2a', 'M', 'Apps grid density per size class: iOS-sized icons (60 px on iPhone, 76 px on iPad) with the house tile gradient, labels at caption size, 4 columns on phone and 6-8 on iPad.', 'The grid looks like a web page of cards, not a home screen.'],
  'UX-HOME-3': ['2a', 'M', 'On iPhone, Home becomes a short glance: a compact hero and horizontally paged cards (or a two-column small-card grid), with reminders reachable in one screen.', 'The phone Home is 4.7 screens tall; reminders and the feed are never seen.'],
  'UX-HOME-4': ['2a', 'S', 'The viewer\'s back button returns to where the app was opened from (Home or Apps), and Escape closes the viewer.', 'People lose their place when they close an app.'],
  'UX-HOME-5': ['2a', 'M', 'Keep the last app document alive (hide, do not blank) for a short time when switching, or ask apps to save drafts through `hub.draft(key)`.', 'Half-typed input is lost on a switch.'],
  'UX-HOME-6': ['2a', 'S', 'The Switch-app sheet shows each app\'s tile icon and colour beside its name, in a grid kids can use.', 'Pre-readers cannot use a text-only list.'],
  'GAP-HOME-2': ['A:verses', 'S', 'Add the Verses Home card the app already writes a summary for ("3 verses to review · 12-day streak"), one tap to the trainer.', 'The daily review is 8 taps away though the data for a card exists.'],
  'UX-HOME-7': ['2a', 'M', 'Kid Home becomes picture-first: big tiles for Kid Verse, Prayer, Timer and Tally with the art, stars shown as stars, and no adult reminders block.', 'Ezra and Kiara cannot read the text-heavy Home.'],
  'UX-HOME-8': ['2a', 'S', 'Finishing a household reminder shows an Undo toast for 6 s (the shared undo toast from batch 1) instead of deleting at once.', 'One mis-tap deletes a household reminder for everyone.'],
  'VIS-HOME-2': ['2a', 'S', 'The timer pill reserves its own space (padding on #views while it shows) and sits in the bar area, never on content.', 'It covers headings and reminders.'],
  'VIS-HOME-3': ['2a', 'S', 'Fix the grid gaps and orphaned Kids card at 1024+ px, drop the 34ch cap on the hero summary, and let chips truncate with an ellipsis.', 'Visible layout rough edges on the iPad and desktop.'],
  // ── Profiles, kid mode, kiosk and admin ──
  'UX-PROF-a1': ['2a', 'S', 'The picker drops guests whose expires_at has passed, from the cached list too.', 'A guest whose stay ended is still offered offline.'],
  'UX-PROF-a2': ['2c', 'S', 'The TV\'s "Reading today" pane lists household readers only (not guests), or marks a guest as a guest.', 'Grandma Jo sits dimmed beside the family as if she had not read.'],
  'UX-PROF-a3': ['2a', 'S', 'The picker shows "Offline — you can still sign in as someone who has used this device" before anyone taps, and disables people it cannot sign in.', 'People type a PIN that cannot work.'],
  'UX-PROF-a4': ['2a', 'S', 'The Create-PIN pad names the person ("Create Mea\'s PIN") with their face, and puts focus on the pad.', 'On a shared iPad, nobody can tell whose PIN is being created.'],
  'VIS-PROF-a1': ['1', 'S', 'The PIN dots fill with the chosen person\'s `--accent-strong` (data-accent on the pad), not the signed-out fallback.', 'The pad does not say whose it is.'],
  'GAP-PROF-a1': ['0d', 'M', 'Me → Change my PIN (current PIN, then new PIN twice), server-verified; this also replaces the claim window that Reset PIN opens (P2-PROF-04).', 'The only way to change a PIN opens an account takeover window.'],
  'UX-PROF-a5': ['2a', 'S', 'After a lockout the pad disables itself and counts down ("Try again in 14 min").', 'The pad looks usable while it refuses every PIN.'],
  'UX-PROF-a6': ['0c', 'S', 'A switch resets the theme to the next person\'s own (their cached hub/theme row, or System) and clears the sync counters; the next person lands on Home.', 'The next person gets the previous person\'s look and counters.'],
  'UX-PROF-a7': ['0d', 'S', 'Pairing failures are limited per device fingerprint and per IP with a lower ceiling for the IP, so one bad actor cannot block the household (keep P2-SEC-01\'s per-profile limit).', 'Ten wrong codes lock every home device out of pairing for 15 minutes.'],
  'UX-PROF-a8': ['2a', 'S', 'The "Choose a pairing code" sheet gets Cancel and real labels, and uses the shared sheet (Escape and drag to close).', 'The sheet can only be left by tapping the backdrop.'],
  'UX-PROF-a9': ['2a', 'M', 'Kid-mode shell controls reach 64 px (`--tap` kid base) and carry icons: the tab bar, the viewer bar, Me\'s buttons; hide Notifications and Forget this device for kids.', 'Pre-readers need big, picture-labelled controls.'],
  'GAP-PROF-a2': ['2a', 'M', 'Admin → Household: add or remove a household person, transfer or add an admin (server-checked), set a person\'s kind and hue.', 'The household cannot be managed from the hub; a second admin is impossible.'],
  'P2-PROF-01': ['0c', 'S', 'Pointer to P2-SYNC-07: closed by flushing (never discarding) the previous person\'s family queue before the kiosk signs in.'],
  'P2-PROF-02': ['0c', 'M', 'Queues are keyed per profile and flushed with that profile\'s session before and after a Switch; a stranded queue is flushed the next time that person signs in on the device, never dropped (apps/hub.js:30, index.html:729-733).'],
  'P2-PROF-03': ['0c', 'S', 'Pointer to P2-SYNC-04: closed by re-arming the poll in hub.reset().'],
  'P2-PROF-04': ['0d', 'M', 'Reset PIN no longer leaves an open claim: the admin\'s reset issues a one-time code (shown once to the admin, expiring in 24 h) that the person must enter before creating a new PIN; the admin\'s own reset needs the admin\'s current PIN. Server-side in worker/src/auth.js and index.js.'],
  'P2-PROF-05': ['0d', 'M', 'The Worker enforces kid limits on family data: a kid session may write only the rows its apps write (prayer prayedBy marks, kidverse stars/story, its own person scope), never tombstones family rows of other apps (worker/src/data.js).'],
  'P2-PROF-06': ['0d', 'S', 'Pointer to P2-PROF-04: the admin\'s own reset requires the current PIN.'],
  'P2-PROF-07': ['0c', 'S', 'Pointer to P2-PWA-06: closed by the per-profile activity queue.'],
  'P2-PROF-08': ['A:timer', 'S', 'A Switch keeps the previous person\'s running timer alive on the device (the shell keeps a per-device list of running timers and still beeps and notifies for them), and the new person sees "Mae\'s timer: 3:12" in the pill.'],
  'P2-PROF-09': ['2a', 'M', 'Idle return on shared devices: after N minutes without a touch (default 10, admin-set, decision P5-D5), the Kitchen iPad returns to the picker; adults need their PIN again; the TV is exempt.'],
  'P2-PROF-10': ['2c', 'S', 'On the kiosk, a hash change to #me, #chat or #apps is ignored (showTab refuses them) and the hidden Me controls are removed, not hidden.'],
  'P2-PROF-11': ['2c', 'S', 'Pointer to P2-STAB-11: the TV\'s Switch stops the board\'s timers and logs the kiosk session out on the server.'],
  'P2-PROF-12': ['2a', 'S', 'The picker opens scrolled to the top with its title below the safe area (scrollTop 0 on show, `--safe-top` padding).'],
  'P2-PROF-13': ['0c', 'S', '"Forget this device" first flushes, then calls a new POST /api/device/forget that deletes the device, its sessions and its push subscriptions, then clears local storage.'],
  'P2-PROF-14': ['0c', 'M', 'The Worker never stores an updated_at more than 30 s ahead of its own clock (clamp to server now), and hub.js stamps writes with `Date.now() - hub.skew`; a clock more than 5 min out shows a warning in Me.'],
  'P2-PROF-15': ['0c', 'S', 'On Switch, remove the previous person\'s person-scope caches from localStorage after their queue has flushed.'],
  'P2-PROF-16': ['2b', 'S', 'The Worker refuses push subscribe and test for the kiosk (403 read_only) and for kids unless the household allows kid notifications; the Me switch is hidden for them.'],
  'P2-PROF-17': ['2b', 'S', 'Pointer to P2-CHAT-13: Admin → Usage groups by New York day.'],
  'P2-PROF-18': ['2a', 'S', 'kindLabel shows "Guest · until <date>" for guests (index.html:1249).'],
  'P2-PROF-19': ['0c', 'S', '"Forget this device" flushes queued writes first (or refuses while offline with "3 changes not yet saved"), and is shown to adults only.'],
  // ── PIN, session and web security ──
  'P2-SEC-01': ['0d', 'M', 'Rate-limit wrong PINs per profile across all devices (e.g. 10 per hour, then exponential back-off, then admin unlock), in addition to per device; alert the admin by push after repeated failures.'],
  'P2-SEC-02': ['0d', 'S', 'The data API enforces visibleTo (apps.json read at build into the Worker, or a server copy): a profile cannot read or write rows of an app it cannot open; chat takes app visibility from the server copy, never from the request.'],
  'P2-SEC-03': ['0c', 'S', 'A Switch made offline queues the logout and sends it on reconnect; the old token is refused once a new session exists for that device.'],
  // ── Sync ──
  'P2-SYNC-01': ['0e', 'L', 'F260 and the build guide store one row per tick (`done:<week>-<i>`, `step:<id>`) instead of whole maps, as CLAUDE.md prescribes for lists; a one-time client migration splits the old map row and keeps it read-only.'],
  'P2-SYNC-02': ['0b', 'M', 'Prayer writes list settings and prayed-days only after its channels have pulled (hub.loaded); its migrate() never rewrites a row it has not read from the server.'],
  'P2-SYNC-03': ['0b', 'S', 'hub.migrate runs only after a successful pull shows the key absent on the server (as apps/hub.js:391-392 promises), and never for guests.'],
  'P2-SYNC-04': ['0c', 'S', 'hub.reset() clears `wired` (or re-creates the 30 s interval and the visibility listener) so polling resumes after every in-page switch (apps/hub.js:338-342, 370).'],
  'P2-SYNC-05': ['0b', 'S', 'F260 writes weekStart only when a week really starts (first tick), never on a first open without data (apps/f260.html:909, 938).'],
  'P2-SYNC-06': ['0c', 'S', 'flush() sends at most 200 rows per request and loops until the queue is empty; a 4xx on one row drops only that row and says so (apps/hub.js:257-264); Prayer\'s import reports the server\'s answer, not "Backup restored."'],
  'P2-SYNC-07': ['0c', 'S', 'Before the kiosk signs in on a device, flush the previous adult\'s family queue with their session (or keep it for their next sign-in); the kiosk never inherits or empties another person\'s queue.'],
  'P2-SYNC-08': ['0c', 'S', 'Pointer to P2-PWA-06.'],
  'P2-SYNC-09': ['0c', 'S', 'hub.reset() aborts in-flight pulls (AbortController) and pull() discards any response whose session token is not the current one before saving it (apps/hub.js:305).'],
  'P2-SYNC-10': ['2a', 'S', 'Pointer to P2-PWA-05.'],
  'P2-SYNC-11': ['0c', 'S', 'A 401 for a token that is no longer current is ignored (compare the request\'s token with hub.session before signing out).'],
  'P2-SYNC-12': ['2c', 'S', 'The TV caches the day\'s reading state it needs (the F260 family summaries), not the last 30 feed lines, so an offline reopen still knows who read.'],
  'P2-SYNC-13': ['2a', 'S', 'Me\'s Sync card (and the album and rewards) re-render on hub.onSync / onChange, like the tab-bar dot.'],
  'P2-SYNC-14': ['2a', 'S', 'Keep `hub.sync.lastPull` per device in localStorage and show it with its date ("Last synced 8:41 am").'],
  'P2-SYNC-15': ['0b', 'S', 'hub.sync.state starts as "pending" (not "offline") until the first pull answers; apps and Home show loading states, not "empty", until then.'],
  'P2-SYNC-16': ['0c', 'S', 'A failed queue write (QuotaExceededError) shows a toast and keeps the change in memory; hub.js trims the oldest caches of other people first.'],
  'P2-SYNC-17': ['0b', 'M', 'The F260 Done tap is refused (button disabled, "Loading your progress…") until the f260 channel has pulled once; with the per-tick rows of 0e a stale tap could no longer erase history anyway.'],
  'P2-SYNC-18': ['0c', 'S', 'refreshScope fires onChange for every key whose value changed when it adopts another window\'s store (apps/hub.js:190-195).'],
  'P2-SYNC-19': ['0e', 'M', 'Encode the journal ciphertext with a chunked base64 (no String.fromCharCode.apply), check the save succeeded before saying "Saved", and say "Not saved — …" on failure.'],
  'P2-SYNC-20': ['0e', 'S', 'Build the new vault object as a copy and replace the stored one only after encryption and encoding succeed, so iv and ciphertext always change together.'],
  'UX-SYNC-a1': ['2a', 'M', 'Every app shows the shared sync status (hub.onSync) in the viewer bar: a small "Saving…" / "Offline — 3 changes waiting" line visible over the app, not only under it.', 'Nobody knows when a change did not sync.'],
  'UX-SYNC-a2': ['2c', 'S', 'The TV\'s "Reading today" reads the F260 family summaries (readOn === today) instead of feed lines, and refreshes on the normal pull.', 'The TV lags five minutes and can credit the wrong person.'],
  'GAP-SYNC-a1': ['0c', 'S', 'Call navigator.storage.persist() after pairing, and tell Safari-tab users on iPhone to add the hub to the Home Screen.', 'A Safari tab can lose queued writes and its pairing after 7 days without a visit.'],
  // ── 24/7 stability ──
  'P2-STAB-01': ['0a', 'S', 'hub.js assigns `hub.sheenFrom = () => {}` before its reduced-motion early return (apps/hub.js:442-447), and index.html:662 calls it only if it is a function.'],
  'P2-STAB-02': ['0c', 'S', 'Pointer to P2-SYNC-04.'],
  'P2-STAB-03': ['0g', 'S', 'Prayer computes TODAY from hub.today() at each tap and on the midnight event (apps/prayer.html:712), and an adult\'s tap never removes a mark dated yesterday.'],
  'P2-STAB-04': ['0b', 'S', 'Pointer to P2-HOME-02.'],
  'P2-STAB-05': ['2b', 'S', 'Pointer to P2-PWA-09.'],
  'P2-STAB-06': ['2a', 'S', 'Pointer to P2-PWA-05.'],
  'P2-STAB-07': ['0b', 'S', 'F260 and Kid Verse re-render on hub.onDay (the midnight event from 0b) and on visibilitychange when the day key changed.'],
  'P2-STAB-08': ['A:timer', 'S', 'Store the timer\'s endAt in server time (Date.now() - hub.skew when writing, + hub.skew when reading) so every device counts down to the same instant; a device only clears a timer it has seen end in server time.'],
  'P2-STAB-09': ['A:timer', 'S', 'The Timer app requests the wake lock itself while a timer runs (the iframe is allowed screen-wake-lock) and the shell re-requests on any visibilitychange while one runs.'],
  'P2-STAB-10': ['2b', 'S', 'Pointer to P2-PWA-15.'],
  'P2-STAB-11': ['2c', 'S', 'The TV\'s Switch stops the board\'s intervals and crossfade loop before showing the picker, and logs the kiosk session out.'],
  'P2-STAB-12': ['2c', 'S', 'The kiosk requests the wake lock on load and on every visibilitychange, and shows a one-time "Tap to keep the screen on" hint only if the request is refused.'],
  'P2-STAB-13': ['A:timer', 'S', 'A device clears timer.active only if the stored record is the one it saw end (same startedAt), using server time; a newer timer is never cleared.'],
  // ── Hub chatbot ──
  'P2-CHAT-01': ['0i', 'M', 'set_data may write only keys of the calling app\'s own documented shapes (a server allowlist per app), never tombstones or overwrites family rows wholesale; every write returns an undo token the chip offers.'],
  'P2-CHAT-02': ['0d', 'S', 'Chat enforces kid limits on the server: for a kid session, set_data and add_list_item are refused on the park map\'s adult rows and every adult-only app.'],
  'P2-CHAT-03': ['0i', 'S', 'finish_leftover matches an item only by exact name (case-insensitive) or asks which one when several match; it never picks by a shared word.'],
  'P2-CHAT-04': ['0i', 'S', 'toggle_f260_reading becomes set_f260_reading {done: true|false}; asking to tick a ticked reading is a no-op that says so.'],
  'P2-CHAT-05': ['2b', 'S', 'The Worker times out a silent upstream after 45 s and the Chat tab offers Cancel while a reply streams.'],
  'P2-CHAT-06': ['0d', 'S', 'Pointer to P2-SEC-02: chat takes visibility and names from the server.'],
  'P2-CHAT-07': ['0d', 'S', 'get_data refuses `.vault` keys by name as the listing already hides them (worker/src/chat.js).'],
  'P2-CHAT-08': ['2b', 'S', 'Make the cap check atomic (INSERT … WHERE (SELECT count(*) …) < cap, or a counter row updated in one statement).'],
  'P2-CHAT-09': ['0i', 'S', 'After putOne, compare the stored row with the written value; if last-write-wins kept a newer row, return ok:false with "Someone else changed it just now" and no ✓.'],
  'P2-CHAT-10': ['2b', 'S', 'Count a message against the cap only when the upstream answered (insert the usage row after a successful first event).'],
  'P2-CHAT-11': ['2b', 'S', 'Keep thinking blocks (with their signatures) in the tool-loop message history as the API requires.'],
  'P2-CHAT-12': ['2b', 'S', 'The system prompt marks the admin and omits expired guests.'],
  'P2-CHAT-13': ['2b', 'S', 'Admin → Usage groups chat and push by New York day, the same day the cap uses.'],
  'P2-CHAT-14': ['2c', 'S', 'Pointer to P2-PROF-10.'],
  'UX-CHAT-01': ['2a', 'S', 'For kids, every chat reply is spoken (speakForKid on each message) and a speaker button replays it.', 'Pre-readers cannot read chat replies.'],
  'UX-CHAT-02': ['2a', 'S', 'Failed sends keep the typed text, show a plain-English error with Retry, and queue offline messages until online.', 'People lose what they typed and see raw errors.'],
  'UX-CHAT-03': ['2a', 'S', 'Failed or refused tools show a red chip ("Couldn\'t add milk: …"); the client renders chips with ok:false.', 'Silent failures look like success.'],
  'UX-CHAT-04': ['2a', 'S', 'At the cap, Send is disabled, the counter is pinned above the composer and the placeholder says "Back tomorrow".', 'The cap is invisible until a send fails.'],
  'UX-CHAT-05': ['2a', 'S', 'The Chat tab shows only the messages the model still has (the 36 h window), with a divider "Earlier messages are not remembered".', 'The tab implies Claude remembers what it does not.'],
  'UX-CHAT-06': ['2a', 'S', 'set_data chips and feed lines use human names ("Saved a photo to the album"), never storage keys.', 'Raw keys show on Home and the TV.'],
  'UX-CHAT-07': ['2a', 'S', 'Day separators and times in the chat log.', 'Old answers read as current.'],
  'GAP-CHAT-01': ['2b', 'S', 'Me → Chat history → Clear (and a 90-day retention for kids\' chat).', 'Kids\' chat history is kept forever.'],
  'GAP-CHAT-02': ['0i', 'M', 'Every chat write returns an undo token; the chip carries Undo for 30 s (an "undo_last" path in chat.js that restores the previous row).', 'Chat acts at once with no way back.'],
  'PWA-UX-3': ['2a', 'S', 'Pointer to PWA-UX-4 and P2-PWA-17 (the composer items).'],
  // ── Notifications, voice add, activity feed, PWA install ──
  'P2-PWA-01': ['0d', 'S', 'Praying for or answering a private request posts no title: "Prayed for a private request" or no line at all (apps/prayer.html:1606, 1329); the Worker refuses activity text for person-scope prayer rows.'],
  'P2-PWA-02': ['2b', 'S', 'parkJob runs on every cron firing (every 15 min on park days, a new cron entry) and treats a kid as stale after 20 min without an update.'],
  'P2-PWA-03': ['2b', 'M', 'Push subscriptions are per person per device: Switch unsubscribes (or re-keys) the previous person, and Me shows the switch for the signed-in person only.'],
  'P2-PWA-04': ['2b', 'S', 'The prayer announcement keeps a per-adult "last announced" stamp and announces every row newer than it at the next run, instead of once a day.'],
  'P2-PWA-05': ['2a', 'S', 'loadFeed refreshes on every pull (reset feedFresh on hub.onSync) and on becoming visible.'],
  'P2-PWA-06': ['0c', 'S', 'The activity queue is per profile (hub.aqueue.<pid>), stamped with the author and time at queue time, and drained by that person\'s session only.'],
  'P2-PWA-07': ['1', 'S', 'Pointer to P2-VIS-03.'],
  'P2-PWA-08': ['2b', 'M', 'An always-open hub checks for a new service worker on visibility and hourly, and applies it at an idle moment (no input focused, no app open) with a reload that restores the tab.'],
  'P2-PWA-09': ['2b', 'S', 'Precache and revalidate with `cache: "reload"` so a VERSION bump never stores the HTTP-cached old files (sw.js:22, 47).'],
  'P2-PWA-10': ['2b', 'S', 'Subscribe validates keys, and pushTo wraps encrypt() in the per-row try so one bad row is skipped and deleted, not fatal to the job.'],
  'P2-PWA-11': ['2b', 'S', 'Only a 2xx from the push service counts toward the daily gate.'],
  'P2-PWA-12': ['2b', 'S', 'The test sends to this device\'s subscription endpoint only (the client sends its endpoint with the request).'],
  'P2-PWA-13': ['0c', 'S', 'One drain at a time (a promise lock around the activity flush).'],
  'P2-PWA-14': ['0c', 'S', 'On a 401 keep the queued line and retry after the next sign-in; discard it only when its author signs out.'],
  'P2-PWA-15': ['2b', 'S', 'Show "Hub updated" only when a previous controller existed before this page load (not on the first install).'],
  'P2-PWA-16': ['2b', 'S', 'Serve a styled offline page (in the hub\'s tokens) for uncached documents, with "Open this app once online to keep it offline".'],
  'P2-PWA-17': ['2a', 'S', 'The chat composer uses the side safe-area insets (margin-left/right: max(var(--margin), env(safe-area-inset-*))).'],
  'P2-PWA-18': ['A:dollywood-live', 'S', 'Add the "Rally the family here" action to the meeting-point bar and the ride card (adults only), calling the existing rally().'],
  'PWA-GAP-1': ['A:timer', 'M', 'A server-scheduled "Timer done" push: the Timer posts endAt to the Worker (POST /api/timer), and a cron or Durable alarm pushes at the end to the owner\'s devices.', 'A timer that ends while the phone is locked is silent.'],
  'PWA-GAP-2': ['2b', 'S', 'Handle pushsubscriptionchange in sw.js by re-subscribing and posting the new subscription.', 'Rotated subscriptions silently stop receiving.'],
  'PWA-UX-1': ['2b', 'S', 'Pointer to P2-PROF-16.'],
  'PWA-UX-2': ['2b', 'S', 'Household pushes (leftovers, prayer, park) exclude guests unless the household opts in.', 'Guests get household nudges.'],
  'PWA-GAP-3': ['2a', 'S', 'Add the mic (hub.voiceInput) to Home\'s "Add a reminder" field.', 'Voice add is missing where hands are busy.'],
  'PWA-UX-4': ['2a', 'S', 'A kid\'s spoken question sends itself when speech ends.', 'A pre-reader cannot check the text or find Send.'],
  'PWA-VIS-1': ['2a', 'S', 'Pointer to P2-HOME-06.'],
  'PWA-VIS-2': ['2a', 'S', 'Pointer to P2-PWA-17.'],
  'PWA-VIS-3': ['2a', 'S', 'Pointer to P2-PROF-12.'],
  'PWA-VIS-4': ['2c', 'S', 'On a portrait kiosk iPad the board stacks panes in one column so each feed line has the full width.', 'Feed lines show 2-3 words.'],
  'PWA-GAP-4': ['2b', 'S', 'Complete the manifest: id, display_override, lang, shortcuts, a maskable and a monochrome icon, an opaque apple-touch-icon, and theme colours that follow the bootstrap.', 'Install quality on iOS and Android.'],
  // ── Shell visual fidelity ──
  'P2-VIS-01': ['0a', 'S', 'Pointer to P2-STAB-01.'],
  'P2-VIS-02': ['2c', 'M', 'The TV shows as many reminders as fit and a "+3 more" line; the list is newest first; the prayed-today faces wrap into a fixed-height row.'],
  'P2-VIS-03': ['1', 'S', 'Hearth sets data-theme="hearth" (the bootstrap always writes the resolved palette, apps/hub.js:77), so only System follows the OS.'],
  'P2-VIS-04': ['0b', 'S', 'Pointer to P2-SYNC-15.'],
  'P2-VIS-05': ['2a', 'S', 'The Kids card truncates the name with an ellipsis and keeps ★ and badge counts visible.'],
  'P2-VIS-06': ['1', 'S', 'The dark hero becomes a deep tint with the glowing ink (`--hero-bg` + `--accent-ink`, Phase 4 batch-1a row for .ds .hero), gated at 4.5:1 for every person in every palette.'],
  'P2-VIS-07': ['2a', 'S', 'Pointer to P2-SYNC-13.'],
};
