// Phase 5 fixes: F260, Verses and Kid Verse (audits/03-apps/f260.md, verses.md, kidverse.md).
// F260 keeps its layout and element ids (CLAUDE.md "Do not touch"): its fixes are data code, copy and token restyling only.
export default {
  // ── F260 ──
  'P3-F260-01': ['0e', 'M', 'One row per verse (`recall:<id>`) that both apps merge field by field: F260\'s practice rating writes only {s, t} into the verse\'s row and never replaces box/due/last/streak (apps/f260.html:1915 → merge; apps/verses.html:296).'],
  'P3-F260-02': ['A:f260', 'S', 'After an untick, remove log[today] when no reading ticked today remains, and let the summary and the 8 pm nudge follow.'],
  'P3-F260-03': ['A:f260', 'S', 'Treat an unread today as pending: the streak walk starts from yesterday when today is unread (as index.html:837-844 already does for prayer).'],
  'P3-F260-04': ['A:f260', 'S', 'When the total drops below 260, clear finished and summary.finished so the nudges resume.'],
  'P3-F260-05': ['0b', 'S', 'Viewing the plan writes nothing: weekStart and the summary are written on the first tick or setting change, never on open.'],
  'P3-F260-06': ['0b', 'S', 'The day key is hub.today() (America/New_York), so a device in another zone files the household\'s date.'],
  'P3-F260-07': ['A:f260', 'S', 'Undo restores the previous current week and removes the start date the Done just created.'],
  'P3-F260-08': ['A:f260', 'S', 'Rename the heatmap\'s today class (e.g. .heat .is-today) so it no longer matches the Today card\'s rules.'],
  'P3-F260-09': ['A:f260', 'S', 'Reading mode keeps #reflect visible (fix the rule order so `.readmode .side` hides only the other children).'],
  'P3-F260-10': ['A:f260', 'S', 'Floor the percentage and cap it at 99 below 260; show at least 1 % once one reading is done.'],
  'P3-F260-11': ['A:f260', 'S', 'Choose "week"/"weeks" from the rounded number.'],
  'P3-F260-12': ['A:f260', 'S', 'Unlock copy that is true everywhere: "Encrypted with your passcode. It follows you to your devices; the passcode never leaves this one."'],
  'P3-F260-13': ['0e', 'M', 'The vault carries a version (a random id per erase/re-create); a device holding an older version refuses to write and asks to unlock again, so an erased or re-created vault is never overwritten.'],
  'P3-F260-14': ['0e', 'S', 'Face ID wraps are per device (`vault.prf[<deviceId>]`), so each device enables its own and other devices hide the button.'],
  'P3-F260-15': ['A:f260', 'S', 'The Erase and Restore confirms say "on all your devices".'],
  'P3-F260-16': ['A:f260', 'S', 'Reset keeps the Verses schedule (box/due/last/streak) or names it in the confirm, with the Undo proposed in F260 §7.'],
  'P3-F260-17': ['A:f260', 'S', 'Save a HEAR entry or week note only when its text changed; keep the date of an unchanged entry.'],
  'P3-F260-18': ['A:f260', 'S', 'Set weekStart when a week\'s first reading is ticked; clamp the shown duration to at least 1 day.'],
  'P3-F260-19': ['A:f260', 'S', 'Browsing weeks records no start date; a start is written only when a week is begun.'],
  'P3-F260-20': ['A:f260', 'S', 'Search highlights by matching the raw text and escaping each piece separately before joining with <mark>.'],
  'UX-F260-1': ['A:f260', 'S', 'Replace every "this device" in the footer, Restore sheet and journal empty state with what is true: it follows you to every device.', 'The copy tells people to fear losing data that is synced.'],
  'UX-F260-2': ['A:f260', 'S', 'Reset keeps a 30-day snapshot and offers Undo.', 'Reset cannot be undone.'],
  'UX-F260-3': ['A:f260', 'S', 'The Journal tab shows its locked state with an Unlock button instead of opening the passcode dialog at once.', 'The dialog pops up every time.'],
  'UX-F260-4': ['A:f260', 'S', 'Reading mode\'s exit button reads "Close" (with an icon), so only the Today card says Done.', 'Two different Done buttons.'],
  'UX-F260-5': ['0b', 'S', 'Until the first pull, Done is disabled with "Loading…", and the stats show skeletons.', 'A live-looking Done does nothing.'],
  'UX-F260-6': ['A:f260', 'S', 'Open the weeks pane scrolled to the current week.', 'The current week is 2,800-4,100 px down.'],
  'UX-F260-7': ['A:f260', 'S', '"Practice again" chips at var(--tap), collapsed to "Practise 14 verses" when there are more than three.', 'Small chips push Day 1 below the fold.'],
  'UX-F260-8': ['A:f260', 'S', 'A settings button in the page header (restyle only; the #settingsBtn id stays).', 'Settings is 1,600 px down on the phone.'],
  'UX-F260-9': ['A:f260', 'S', 'Say "last read" once in the hero.', 'Repetition.'],
  'UX-F260-10': ['A:f260', 'S', 'The sort button toggles its label ("Oldest first") and aria-pressed.', 'The label never changes.'],
  'UX-F260-11': ['A:f260', 'M', 'A "Journal" action on the Today card that opens today\'s HEAR entry after unlock.', 'Six taps and a long scroll to write today\'s entry.'],
  'UX-F260-12': ['1', 'M', 'The Today card uses the glance roles on the iPad (today\'s reading at --fs-glance-2).', 'Nothing in F260 reads across the kitchen.'],
  'UX-F260-13': ['A:f260', 'S', 'After today\'s tick the primary button reads "Read ahead" (or hides), with "Read today ✓" as the state.', 'Done under the next reading invites a second tick.'],
  'UX-F260-14': ['A:f260', 'S', 'Hide the Next up hero when it repeats the Today card.', 'The same reading twice on one screen.'],
  'VIS-F260-1': ['1', 'M', 'Secondary text reads --text-2/--text-3 and hue text reads -ink tokens (batch-1a pre-pass rows for F260), no opacity dimming.', 'Much of F260\'s secondary text fails AA.'],
  'VIS-F260-2': ['1', 'S', 'Empty cells use --cell-empty (a ≥ 3:1 ring) in every palette.', 'Empty progress is invisible.'],
  'VIS-F260-3': ['A:f260', 'S', 'Reserve the loaded heights (--min-h-* tokens) so the data arriving does not shift the page.', 'CLS 0.24 on a cold open.'],
  'VIS-F260-4': ['A:f260', 'S', 'Disabled .seg buttons get --op-disabled and cursor default.', 'Disabled buttons look enabled.'],
  'VIS-F260-5': ['A:f260', 'S', 'Style the week-note footer like the HEAR footer (13 px, 44 px Copy).', 'An unstyled footer.'],
  'VIS-F260-6': ['A:f260', 'S', 'Hide WebKit\'s search cancel glyph (appearance: none on ::-webkit-search-cancel-button) and ring the pill with :focus-within.', 'Two clear buttons.'],
  'VIS-F260-7': ['A:f260', 'S', 'Print read state (a ✓ per read reading) and give week headers a straight rule.', 'The printed plan shows no progress.'],
  'VIS-F260-8': ['A:f260', 'S', 'Style .help locally (footnote size, --text-3).', 'The hint renders as body text.'],
  'VIS-F260-9': ['A:f260', 'S', 'Keep Undo beside Done at 1180 and 1440 px.', 'Undo wraps.'],
  'VIS-F260-10': ['1', 'S', 'Large text becomes the hub text size (decision D17) through --ts-user instead of zoom, so lines reflow.', 'Large text wraps the meta line.'],
  'VIS-F260-11': ['1', 'S', 'Done, the ring and progress read --accent-strong / --progress-fill (the person\'s colour).', 'The person\'s accent never reaches F260.'],
  'VIS-F260-12': ['A:f260', 'M', 'user-select: none on chrome, the shared switch for "Show passcode", Lucide icons for milestones, targets to var(--tap).', 'Web tells.'],
  'VIS-F260-13': ['A:f260', 'S', 'Let the current week\'s subtitle wrap under the badges on the phone.', 'The start date is cut off.'],
  'VIS-F260-14': ['1', 'S', 'The Done toast uses the shared bottom toast.', 'The toast covers the title.'],
  'VIS-F260-15': ['A:f260', 'S', 'Disable Search, sort and Copy all while the journal is locked or empty; give "Set passcode" room.', 'Dead controls look live.'],
  'VIS-F260-16': ['1', 'S', 'Modals use --material-chrome-bg at the proposed 90 % alpha (info).', 'Rows show through the modal.'],
  'GAP-F260-1': ['A:f260', 'M', 'Catch-up: "Missed: Day 2 of Week 31" offered first, and a "Catch up" row in the Today card when an earlier week has gaps.', 'A missed reading is not offered for 73 readings.'],
  // ── Verses ──
  'P3-VERSES-01': ['0e', 'S', 'Pointer to P3-F260-01 (per-verse merged recall rows).'],
  'P3-VERSES-02': ['0e', 'M', 'One row per verse (`recall:<id>`) and a per-day review count row, so two devices\' ratings both survive.'],
  'P3-VERSES-03': ['0b', 'S', 'No rating until the f260 and verses channels have pulled once (buttons disabled, skeleton card).'],
  'P3-VERSES-04': ['0b', 'S', 'Re-render on hub.onDay and on visibilitychange when the day changed.'],
  'P3-VERSES-05': ['A:verses', 'S', 'The Not yet toast states the real next review ("again in 2 days").'],
  'P3-VERSES-06': ['A:verses', 'S', 'Read aloud stays after Show and reads the verse text when F260 has it.'],
  'P3-VERSES-07': ['0b', 'S', 'A loading state until the first pull, and no summary write before it.'],
  'P3-VERSES-08': ['A:verses', 'S', 'Extra practice shows as practice; the due count and Due today list keep the real due set.'],
  'P3-VERSES-09': ['0b', 'S', 'Reviews use hub.today() (New York).'],
  'P3-VERSES-10': ['A:verses', 'S', 'The Show shortcut applies only when no button has focus; Enter/Space activate the focused button.'],
  'P3-VERSES-11': ['A:verses', 'S', 'A day with nothing due keeps the streak.'],
  'P3-VERSES-12': ['A:verses', 'S', 'Ignore a second tap within 400 ms of a rating; the next card arrives with a short transition.'],
  'P3-VERSES-13': ['A:verses', 'S', 'aria-hidden on the veiled text until Show.'],
  'P3-VERSES-14': ['A:verses', 'S', 'Empty-state copy: "Mark a memory verse as memorised in F260 and you can review it here straight away", with a button to F260.'],
  'UX-VERSES-1': ['A:verses', 'M', 'Kid practice: the paraphrase from Kid Verse is read aloud, big picture buttons (a star for "Got it", a smile for "Almost"), no reading needed.', 'A pre-reader cannot practise at all.'],
  'UX-VERSES-2': ['A:verses', 'S', 'An Undo toast after each rating restores the previous box, due date and streak.', 'A mis-tap cannot be undone.'],
  'UX-VERSES-3': ['A:verses', 'S', 'Pointer to GAP-HOME-2: the Home card built from verses.summary brings the review to one tap.', 'Eight taps from Home.'],
  'UX-VERSES-4': ['A:verses', 'S', 'Say "Nothing due today" without the celebration star, and "all done" only after reviews.', 'Wrong celebration.'],
  'UX-VERSES-5': ['0b', 'S', 'Show the skeleton card while loading.', 'A blank page with an empty pill.'],
  'UX-VERSES-6': ['1', 'S', 'The shared toast sits above the tab bar and never over the stats card.', 'The toast covers labels.'],
  'UX-VERSES-7': ['1', 'S', 'Glance roles for the reference and counts on the Kitchen iPad.', 'Only the reference reads past 1.5 m.'],
  'UX-VERSES-8': ['A:verses', 'S', 'Say the due count once (the pill), not three times.', 'Repetition.'],
  'UX-VERSES-9': ['A:verses', 'S', 'Replace box jargon with intervals ("Next review in 4 days").', 'Leitner jargon.'],
  'VIS-VERSES-1': ['A:verses', 'S', 'Size the trainer card to its content; no fixed min-height after Show.', 'Empty glass.'],
  'VIS-VERSES-2': ['1', 'S', 'The trainer and done cards become solid material (--material-solid-bg).', 'Live glass on content in a scroller.'],
  'VIS-VERSES-3': ['1', 'S', '"Got it" becomes --success-strong with its -on label (≥ 4.76:1) in every palette.', 'The most-tapped control fails AA in Hearth.'],
  'VIS-VERSES-4': ['1', 'S', 'Light primaries follow the pairing rule (--accent-strong / --accent-on) (decision D15).', 'Inverted fill/ink.'],
  'VIS-VERSES-5': ['1', 'S', 'One display weight (the bold system title) per card.', 'Two weights of the serif.'],
  'VIS-VERSES-6': ['A:verses', 'S', 'Tint the histogram by box, not by count (info).', 'The tint encodes the wrong thing.'],
  'VIS-VERSES-7': ['1', 'S', 'Dark fills from the pastel family (deep tints, not browns) through the token change.', 'Muddy dark fills.'],
  'GAP-VERSES-1': ['A:verses', 'M', 'Verse text available for every memorised verse (store the pasted text once per verse in the family scope, or offer paste inside Verses).', 'Show reveals nothing for most cards.'],
  'GAP-VERSES-2': ['A:verses', 'S', 'Not yet sends a verse back to box 1 (standard Leitner) and each button shows its next interval.', 'Forgotten verses stay near the top box.'],
  'GAP-VERSES-3': ['A:verses', 'S', 'The empty state gets an "Open F260" button.', 'No way forward from the empty state.'],
  // ── Kid Verse ──
  'P3-KIDVERSE-01': ['0b', 'S', 'Done ★ stays disabled (with a spinner-free "Getting your stars…" state) until the kidverse channels have pulled once; reconcile never runs on an unloaded row.'],
  'P3-KIDVERSE-02': ['0f', 'L', 'One row per earned star (`star:verse:<date>`, `star:story:<date>`, `star:prayed:<date>`), with count, total and badges derived; the family mirror is recomputed from them, so two devices\' stars add up.'],
  'P3-KIDVERSE-03': ['0b', 'S', 'The week stepper stays disabled until the family scope has pulled.'],
  'P3-KIDVERSE-04': ['A:kidverse', 'S', 'Each day dot shows every star earned that day (star, book and heart marks), or the row is labelled as the verse row.'],
  'P3-KIDVERSE-05': ['A:kidverse', 'S', 'A week change repaints the story card.'],
  'P3-KIDVERSE-06': ['A:kidverse', 'S', 'Label the balance "to cash in" and show earned as "869 ever".'],
  'P3-KIDVERSE-07': ['0g', 'S', 'Prayer records prayedBy as profile ids (names drawn at render), and Kid Verse matches by id (with P3-PRAYER-24).'],
  'P3-KIDVERSE-08': ['0b', 'S', 'One star per household day via hub.today().'],
  'P3-KIDVERSE-09': ['A:kidverse', 'S', 'Fold credited days older than the look-back into counters; upload once per change.'],
  'P3-KIDVERSE-10': ['0f', 'M', 'One row per heard day (`heard:<week>:<date>`), so two devices never erase each other\'s heard days.'],
  'P3-KIDVERSE-11': ['0b', 'S', '"I heard it" is disabled until the story rows have pulled once.'],
  'P3-KIDVERSE-12': ['A:kidverse', 'S', 'A reset row carries the verse days it clears, and Kid Verse applies them whatever the current ISO week.'],
  'P3-KIDVERSE-13': ['A:kidverse', 'S', 'A reset marks story and prayed days up to its date as reset before crediting (time-stamped marks for the reset\'s own day).'],
  'P3-KIDVERSE-14': ['1', 'S', 'The star buttons paint from --star-fill / --star-stroke (the butter family) for every kid.'],
  'UX-KIDVERSE-1': ['A:kidverse', 'M', 'Distinct pictures for the two speaker buttons (a verse scroll, a storybook), a big picture "I heard it" (an ear + star), and spoken toasts.', 'Several kid steps need reading.'],
  'UX-KIDVERSE-2': ['A:kidverse', 'M', 'Kid layout: the art, the speaker and Done ★ fit the first screen on every device; the story card follows.', 'Done ★ is below the first screen.'],
  'UX-KIDVERSE-3': ['0d', 'S', 'Only household adults step the family week (the Worker refuses guests).', 'Guests can change the household\'s week.'],
  'UX-KIDVERSE-4': ['A:kidverse', 'S', 'After a reset, the story card and the stars card agree ("Heard 1 day · no stars this week").', 'Contradictory cards.'],
  'UX-KIDVERSE-5': ['A:kidverse', 'S', 'With no family week, adults get "Pick this week\'s verse" and kids a friendly placeholder.', 'Week 1 shows silently.'],
  'UX-KIDVERSE-6': ['0b', 'S', 'Skeleton art and text of the loaded size until the week arrives.', 'Placeholders then a 368 px jump.'],
  'UX-KIDVERSE-7': ['2a', 'S', 'Pointer to UX-SYNC-a1 (the shared pending state in the viewer bar).', 'An offline star looks saved.'],
  'UX-KIDVERSE-8': ['1', 'S', 'The shared toast (bottom, dismissible) replaces the tall text toasts.', 'Toasts cover the story card.'],
  'UX-KIDVERSE-9': ['A:kidverse', 'S', 'Show the year on dates older than this year.', 'Badge dates have no year.'],
  'UX-KIDVERSE-10': ['A:kidverse', 'S', 'For adults, the Kids\' stars panel and week stepper come first.', 'The adult\'s job is two screens down.'],
  'VIS-KIDVERSE-1': ['1', 'S', 'Day letters, badge hints and the unearned glyph read --text-3 on --surface-2 (≥ 4.5:1), at --fs-caption2 minimum.', 'They fail text contrast.'],
  'VIS-KIDVERSE-2': ['1', 'S', 'The today ring reads --today-ring and empty dots --cell-empty (≥ 3:1).', 'The day strip is nearly invisible.'],
  'VIS-KIDVERSE-3': ['1', 'S', 'Unearned badges get a ≥ 3:1 outline and a visible glyph in dark.', 'Black blanks in dark mode.'],
  'VIS-KIDVERSE-4': ['1', 'S', 'Pointer to P3-KIDVERSE-14.', 'See P3-KIDVERSE-14.'],
  'VIS-KIDVERSE-5': ['A:kidverse', 'S', 'The grown-ups panel gives each kid\'s name and ★ count their own line on the iPhone.', 'The dots cover the count.'],
  'VIS-KIDVERSE-6': ['1', 'M', 'Story art sits on --art-plate; scripts/make-art.mjs emits token-friendly fills (a dark variant).', 'A pale panel glares on dark pages.'],
  'VIS-KIDVERSE-7': ['1', 'S', 'Kid mode reaches every role (--fs-floor 16) and numerals are rounded.', '10 px text and serif numerals in kid mode.'],
  'VIS-KIDVERSE-8': ['1', 'S', 'Scene and story cards become solid material; radii concentric.', 'Glass on content.'],
  'VIS-KIDVERSE-9': ['A:kidverse', 'S', 'Drop the repeated ★/✓ glyphs from labels and use Lucide minus/plus in the stepper.', 'Doubled icons.'],
  'VIS-KIDVERSE-10': ['1', 'S', '-webkit-touch-callout: none and user-select: none on the art and chrome (batch-1b base chrome rules).', 'Long-press menus on the art.'],
  'VIS-KIDVERSE-11': ['A:kidverse', 'S', 'Wrap the rewards summary as separate items without dangling separators.', 'A dangling dot.'],
  'GAP-KIDVERSE-1': ['A:kidverse', 'S', 'Offer "Move to week 39?" on Sunday evening to adults, and post a feed line when the week changes.', 'The week never advances and nobody is told.'],
};
