// Phase 5 fixes: the design-system findings (audits/04-design-system.md). Most close in batch 1, through the Phase 4
// proposal (audits/tools/phase4/tokens/proposed-tokens.css and its batch-1a/1b rows); the gap-row id is named where one exists.
export default {
  'P4-TOK-01': ['1', 'S', 'Focus becomes an outline in --focus-ring-color (the person\'s -graphic, ≥ 3:1) with a surface gap (proposal §2.5, TOK row).'],
  'P4-TOK-02': ['1', 'S', 'The switch reads --switch-off / --switch-off-ring / --switch-knob (≥ 3:1 off and on, both schemes).'],
  'GAP-TOK-1': ['1', 'M', 'contrast.mjs becomes the design gate: every component pair design.css paints (42 kinds) is gated, not only the 15 token pairs; scripts/test-design.mjs runs it.', 'Components fail contrast the tests never check.'],
  'GAP-TOK-2': ['1', 'S', 'An -on token for every fill (--X-on, --accent-on, --badge-ink) and the pairing lint (no white on a fill).', 'Each surface picks white or an ink by hand.'],
  'GAP-TOK-3': ['1', 'M', 'People and apps carry a hue family name (data-accent, apps.json "hue", the profile hue column), re-tuned per scheme.', 'Profile and app colours fail as foregrounds in dark.'],
  'GAP-TOK-4': ['1', 'M', 'Kid and kiosk scale every role through --ts-kind / --space-k / --shape-k; literal sizes move to roles app by app (lint row).', 'Literal sizes escape the kid and TV scales.'],
  'GAP-TOK-5': ['1', 'S', 'Weight, z-index, opacity, press-scale and composite glass tokens (proposal §1).', 'Each area invents its own.'],
  'GAP-TOK-6': ['1', 'S', 'data-accent on any element re-derives every accent role for its subtree.', 'The accent cannot be scoped to a component.'],
  'GAP-TOK-7': ['1', 'S', 'The lint checks every <style> and inline style for hex, rgb() and named colours (screens-apps.mjs extended).', 'The "every colour is a token" rule is checked only partly.'],
  'GAP-TOK-8': ['1', 'S', 'One block per palette; the .tp[data-preview] copies go (data-theme-preview).', 'Dark palettes are stored two or three times.'],
  'GAP-TOK-9': ['1', 'S', 'Retire the three unused tokens and the exact aliases once the lint finds no reader (info).', 'Dead tokens.'],
  'CONS-TOK-1': ['1', 'M', 'App-local vocabularies (F260, Prayer, the Larder, the template) retarget to role tokens in each app\'s batch (migration table).', 'Four meanings of "ink".'],
  'CONS-TOK-2': ['1', 'M', 'One segmented control and one set of component names; non-.ds apps adopt them in their batches.', 'Class names mean different components.'],
  'CONS-TOK-3': ['1', 'M', 'Replace the 168 color-mix() recipes with role tokens (--tint-*, --sel-*, --glass-*).', 'The person colour is mixed at 27 ratios.'],
  'CONS-TOK-4': ['2a', 'S', 'The shell\'s eight off-scale radii become calc(var(--icon-box) * var(--r-icon-ratio)) (info).', 'One ratio typed eight times.'],
  'P4-TYPE-01': ['A:dollywood', 'S', 'Map labels in screen px with an 11 px floor (--fs-caption2), independent of the map scale.'],
  'GAP-TYPE-1': ['1', 'S', 'The iPad type tier (--ts-width 1.12 on touch devices ≥ 744 px).', 'iPad text is phone-sized.'],
  'GAP-TYPE-2': ['1', 'M', 'A person text-size preference (data-text-size xs-xxl; Me → Appearance), F260\'s Large mapped to it (decision D17).', 'No text-size control.'],
  'VIS-TYPE-1': ['2c', 'M', 'The TV\'s information text on the 10-foot scale with the re-laid-out grid (decision D16).', 'TV names and times are 18 px, the date 12 px.'],
  'CONS-TYPE-1': ['1', 'S', 'One large-title role (34 bold, tight tracking) everywhere; apps inside the viewer drop their duplicate title (decision D6).', 'Eight title treatments.'],
  'CONS-TYPE-2': ['1', 'M', 'Every role from the Dynamic Type tokens (--text-*), adopted per app.', 'The same role set seven ways.'],
  'CONS-TYPE-3': ['1', 'S', 'Numerals read --font-numeral with tabular figures in every area.', 'Numerals in four faces.'],
  'CONS-TYPE-4': ['1', 'S', 'The kid block scales every role including captions (--fs-floor 16).', 'Kid captions stay 12 px.'],
  'CONS-TYPE-5': ['1', 'S', 'Kid mode is rounded everywhere (decision D6).', 'Kid display type is serif.'],
  'GAP-TYPE-3': ['1', 'S', 'An 11 px floor in every role (--fs-floor) and a lint for literal sizes below it.', 'Ten components go below 11 px.'],
  'CONS-TYPE-6': ['A:dollywood', 'S', 'The template names real stacks (--font-serif / --font-text) instead of generic families.', 'Headings fall back to Times.'],
  'CONS-TYPE-7': ['1', 'M', 'Literal px sizes move to roles app by app (the lint row per app batch).', 'Five apps bypass the type tokens.'],
  'VIS-TYPE-2': ['A:dollywood', 'S', 'Key/value pairs use --text-label / --text-value (weight and size, not ink alone).', 'Labels and values differ only by ink.'],
  'P4-SHAPE-01': ['1', 'M', 'Kid minimum targets outside .ds: a global kid rule sized from var(--tap) for the Larder and the park map (proposal SHAPE-9; open issue 8 names the owner here).'],
  'P4-SHAPE-02': ['A:prayer', 'S', 'Prayer\'s toast action at var(--tap) (use the shared toast).'],
  'P4-SHAPE-03': ['A:dollywood-live', 'S', 'The five further park-map controls (handle, About, layer rows, heights, …) at var(--tap).'],
  'P4-SHAPE-04': ['1', 'S', 'The shared toast sizes to its content up to --col-narrow, with side margins, not half the viewport.'],
  'CONS-SHAPE-1': ['1', 'M', 'One content card (--r-card, --pad-card, --material-solid-bg, --elev-card) adopted per app.', 'The card is built six ways.'],
  'VIS-SHAPE-1': ['1', 'S', 'Concentric by construction (--r-card = --r-control + --pad-card; --r-inset).', 'Nested corners do not match.'],
  'CONS-SHAPE-2': ['1', 'S', 'Three column tokens (--col-narrow / --col-read / --col-wide) adopted per app.', 'Nine column widths.'],
  'VIS-SHAPE-2': ['1', 'S', 'Margins by size class (16/20/28/32) from --margin with safe areas.', 'Phone margins on the iPad.'],
  'CONS-SHAPE-3': ['1', 'M', 'Own-CSS areas adopt the 4 pt spacing tokens in their batches (lint row).', 'The rhythm splits the system.'],
  'CONS-SHAPE-4': ['1', 'S', 'The primary action is a capsule at --btn-h-lg everywhere.', 'Six shapes for the main action.'],
  'CONS-SHAPE-5': ['1', 'S', 'One sheet (--r-sheet, --elev-overlay) shared by every area.', 'Four sheet radii.'],
  'GAP-SHAPE-1': ['1', 'S', 'Elevation role tokens (--elev-card/-control/-float/-overlay/-toast/-bar-up).', 'No elevation roles.'],
  'CONS-SHAPE-6': ['1', 'S', 'Own-CSS radii move to --r-* roles; the kid radius scale reaches the park map.', 'Off-scale radii.'],
  'VIS-SHAPE-3': ['A:dollywood', 'S', 'The Listings/Layers/Scale switcher becomes the shared segmented control.', 'Square underline tabs.'],
  'VIS-SHAPE-4': ['A:prayer', 'S', 'Pointer to P4-SHAPE-04 (Prayer adopts the shared toast).', 'A short toast wraps.'],
  'P4-ICON-01': ['1', 'S', 'Tiles and card heads read --accent-ink under a data-accent scope (lifted for dark); no raw apps.json or profile hex as ink.'],
  'P4-ICON-02': ['1', 'S', 'The duotone fill is set on the <svg> and inherited through <use> (--icon-duo, --icon-duo-opacity).'],
  'P4-ICON-03': ['1', 'S', 'Icons on gold tints read --butter-ink (the -ink rule).'],
  'P4-ICON-04': ['A:dollywood-live', 'S', 'The compass needle reads --map-north (danger graphic, ≥ 3:1).'],
  'P4-ICON-05': ['1', 'S', 'The .ds icon rule stops overriding stroke-width and fill attributes (vector-effect: non-scaling-stroke with --icon-stroke).'],
  'CONS-ICON-1': ['1', 'L', 'One icon set: a Lucide (ISC) sprite with the licence notice, one weight, --icon-* sizes; apps adopt it in their batches (glyph-by-glyph map in 04 ICON).', 'Eleven icon families.'],
  'CONS-ICON-2': ['1', 'S', 'One drawing per meaning (the ICON meaning map).', 'One drawing, several meanings.'],
  'VIS-ICON-1': ['1', 'M', 'Text glyphs and emoji used as icons become Lucide icons (emoji stay only as people\'s faces).', 'Glyphs stand in for icons.'],
  'GAP-ICON-1': ['1', 'S', 'Icon tokens, size scale, weight and ink rules, and a sprite shown in docs/design.html.', 'No icon system.'],
  'GAP-ICON-2': ['1', 'S', 'Ship the Lucide licence notice (ISC) with the sprite; replace custom look-alikes.', 'Lucide and Feather paths ship without their licence.'],
  'P4-GLASS-01': ['1', 'S', '--sheen-x is written on the two bars only and read by their ::after transform (GLASS-7 component rule), never on :root.'],
  'P4-GLASS-02': ['1', 'S', 'Content cards use --material-solid-bg; the perf guard keys on the material role, not the class pair.'],
  'P4-GLASS-03': ['1', 'S', 'Remove live blurs under opaque fills (Prayer\'s FAB, the park map\'s north button, the steps sheet) in their batches.'],
  'P4-GLASS-04': ['2c', 'S', 'The TV\'s Switch uses the look without a live blur (the kiosk sets --glass-filter none; open issue 14 moves its literal recipe).'],
  'P4-GLASS-05': ['A:tally', 'S', 'Tally\'s dial and pill become solid; glass stays on + and −.'],
  'CONS-GLASS-1': ['1', 'S', 'One glass recipe via --glass-filter and --glass-bg*, replacing 17 re-typed copies.', 'Seventeen copies in three variants.'],
  'CONS-GLASS-2': ['1', 'M', 'Glass on the navigation layer only, in every area (content glass rows per app; open issue 15).', 'Five areas put glass on content.'],
  'CONS-GLASS-3': ['1', 'S', 'The tilt drift is removed (it never runs on iPad or iPhone) (info).', 'Dead code.'],
  'VIS-GLASS-1': ['1', 'S', 'No glass over glass: nested panels inside a glass sheet are solid.', 'Glass on glass.'],
  'VIS-GLASS-2': ['2a', 'S', 'The viewer bar becomes solid material (nothing passes beneath it).', 'Live glass with nothing behind it.'],
  'GAP-GLASS-1': ['1', 'M', 'Reduce Transparency and Increase Contrast blocks (attribute + media mirror) and the Me → Appearance switches (decision D11).', 'No glass responds to accessibility settings.'],
  'P4-MOTION-01': ['2a', 'S', 'The Apps grid re-renders only when the app list changed, and never replays its entrance on a pull.'],
  'P4-MOTION-02': ['2a', 'S', 'The viewer exit is interruptible: a tap during the 220 ms exit is honoured and an app opened then stays open.'],
  'P4-MOTION-03': ['A:dollywood-live', 'S', 'Park-map pulses stop after three cycles (--ambient-iterations) and animate transform/opacity, not box-shadow.'],
  'P4-MOTION-04': ['1', 'S', 'JS smooth scrolls read the reduce-motion state (behavior: "auto" under reduce) in F260, the build guide and the park map.'],
  'CONS-MOTION-1': ['1', 'S', 'The global .pressable (scale 0.97 + dim) adopted in every area.', 'Press feedback is partial outside .ds.'],
  'CONS-MOTION-2': ['1', 'M', 'Literal durations move to the --dur-*/--spring-* tokens app by app (lint row) (info).', '93 literal durations.'],
  'CONS-MOTION-3': ['1', 'M', 'One sheet and one toast component (slide up, animate out, drag to dismiss) shared by all areas.', 'Four sheets and three toast systems.'],
  'CONS-MOTION-4': ['1', 'M', 'One loading primitive: hub.loaded + a skeleton class sized to the loaded box (--sk-line, --min-h-*), used by every app.', 'No shared loading state.'],
  'CONS-MOTION-5': ['1', 'S', 'Reduce Motion handled once (data-motion + mirror + the re-keyed global rule) (info).', 'Five ways.'],
  'GAP-MOTION-1': ['1', 'S', 'Stable heights while loading (--min-h-*), and CLS measured per app in the Phase 6 rerun.', 'Content jumps on cold loads.'],
  'GAP-MOTION-2': ['1', 'S', 'Spring curves as linear() tokens (--spring-snappy/-gentle/-bouncy) (info).', 'No springs.'],
  'GAP-MOTION-3': ['1', 'S', 'hub.js adds a passive touchstart listener so :active shows on iOS in every document.', 'Press states may never show on iPhone or iPad.'],
  'P4-DARK-01': ['1', 'S', 'Pointer to P4-COLOR-02 (text) and P4-ACCENT-04 (the Timer arc).'],
  'P4-DARK-02': ['1', 'S', 'Hearth always writes data-theme (P2-VIS-03 fix), which removes the app-by-app failures.'],
  'P4-DARK-03': ['1', 'S', 'Pointer to P4-COLOR-04.'],
  'P4-DARK-04': ['1', 'S', 'applyTheme updates every theme-color meta on every call, including after a pull.'],
  'GAP-DARK-1': ['1', 'S', 'Dark fills sit ≥ 1.5:1 from the card (deep pastel tints in the proposal).', 'Soft-filled states go muddy.'],
  'GAP-DARK-2': ['1', 'S', 'A lifted depth ladder (wells lighter than cards, raised surfaces lighter still).', 'Wells read as holes.'],
  'GAP-DARK-3': ['1', 'S', 'Pointer to P4-TOK-01.', 'See P4-TOK-01.'],
  'VIS-DARK-1': ['1', 'S', 'Dark toasts on --toast-bg (a raised dark slab), not an inverted light one.', 'The brightest object on a dark screen.'],
  'CONS-DARK-1': ['1', 'M', 'Art with a dark form: scripts/make-art.mjs emits token fills, and art sits on --art-plate meanwhile.', 'Each area improvises dark art.'],
  'P4-ACCENT-01': ['1', 'S', 'Selection uses --sel-fill-strong / --sel-ink-strong (≥ 3:1) plus --sel-weight, a non-colour cue.'],
  'P4-ACCENT-02': ['1', 'S', 'Pointer to P4-COLOR-02.'],
  'P4-ACCENT-03': ['1', 'S', 'Pointer to P4-COLOR-03.'],
  'P4-ACCENT-04': ['1', 'S', 'Person-coloured rings read --accent-graphic (≥ 3:1 per scheme).'],
  'P4-ACCENT-05': ['1', 'S', 'The session profile refreshes on pull, so an admin recolour reaches signed-in people (ACCENT-9, hub.js).'],
  'P4-ACCENT-06': ['A:dollywood-live', 'S', 'The pressed compass keeps its needle and "N" at ≥ 3:1 (a --map-north mark on a neutral fill).'],
  'CONS-ACCENT-1': ['1', 'S', 'Signed out, the accent is graphite (the neutral default), not Elizabeth\'s colour.', 'Every PIN pad looks like Elizabeth\'s.'],
  'CONS-ACCENT-2': ['1', 'S', 'App tiles keep their own hues (D5); a person is always ring + face and a tile always glyph + name, so neither is read by colour alone, even when the admin gives a person an app\'s colour (household answer 2026-09-26); the Timer\'s running ring uses the owner\'s colour, never --danger.', 'One hue means a person, an app and a status.'],
  'CONS-ACCENT-3': ['1', 'S', 'A local accent override is a data-accent scope, which re-derives every role.', 'Overrides do not re-derive.'],
  'CONS-ACCENT-4': ['1', 'S', 'Each app carries the person\'s colour on its primary action, selection and progress (a per-app row).', 'Some apps never show the person\'s colour.'],
  'VIS-ACCENT-1': ['1', 'S', 'Each person starts with a distinct house pastel family (decision D3); the nine people\'s colours are CVD-separated (gated ΔE00). The admin may assign any of the 18 (household answer 2026-09-26); an app colour is not CVD-separated from the people\'s, so the picker\'s CVD check (GAP-ACCENT-1) warns.', 'Profile colours are near-grey and too close.'],
  'GAP-ACCENT-1': ['2a', 'S', 'The admin colour picker (Me → Admin → Edit, for every profile, guests included) offers all 18 named families: the nine people\'s colours first, then the nine app colours, each labelled with the app that uses it. It warns on a duplicate, on a colour an app uses and on a colour a colour-blind viewer would confuse with another person\'s (the CVD check); the admin decides (household answer 2026-09-26). The Worker accepts only the 18 names.', 'The picker cannot keep people apart.'],
  'P4-TELL-01': ['1', 'S', '.ds .btn focus is an outline (--focus-ring), so component box-shadows cannot hide it.'],
  'P4-TELL-02': ['1', 'S', 'Every field at --fs-field (≥ 16 px), so iOS never zooms on focus.'],
  'P4-TELL-03': ['1', 'S', 'The inline <head> bootstrap sets theme, scheme and color-scheme before first paint (bootstrap.js).'],
  'P4-TELL-04': ['1', 'S', 'Thin themed scrollbars (--scrollbar-thumb) on the hub\'s scrollers; hidden on chrome.'],
  'P4-TELL-05': ['A:dollywood', 'S', 'Reserve the chip strip\'s height (--min-h-chips) before the chips arrive.'],
  'P4-TELL-06': ['1', 'S', 'overscroll-behavior on html (base chrome rules), with the page background on html.'],
  'P4-TELL-07': ['1', 'S', 'Apps-grid tiles, picker cards and the chat composer keep a visible outline focus (--focus-ring, outline not shadow).'],
  'CONS-TELL-1': ['1', 'S', 'Base chrome rules (user-select, touch-callout) apply globally, not only inside .ds.', 'Selectable chrome outside .ds.'],
  'CONS-TELL-2': ['1', 'M', 'One confirm sheet and undo toasts replace the 20 native dialog call sites (14 reachable).', 'Native confirm() dialogs.'],
  'VIS-TELL-1': ['A:dollywood', 'S', 'The viewer\'s loading background follows the theme (--viewer-loading-bg), not a dark frame, for the build guide.', 'Light themes open on a near-black frame.'],
  'GAP-TELL-1': ['0b', 'S', 'Pointer to CONS-MOTION-4: hub.loaded gives apps the "pulled" signal the skeletons need.', 'Apps cannot know when to show a skeleton.'],
  'P4-COLOR-01': ['1', 'M', 'The batch-1a pre-pass: text and icons read -ink tokens, fills -fill/-strong, marks -graphic (legacy hue names alias the inks).'],
  'P4-COLOR-02': ['1', 'S', 'The six rules that ink with the raw profile colour read --accent-ink.'],
  'P4-COLOR-03': ['1', 'S', 'The Me hero Switch reads --hero-btn-bg / --hero-btn-ink (the revision-5 batch-1a row; open issue 19 covers its dark edge).'],
  'P4-COLOR-04': ['1', 'S', 'color-scheme follows the chosen palette (every palette block and the bootstrap), so UA controls follow the theme.'],
  'P4-COLOR-05': ['1', 'S', 'Fields get a ≥ 3:1 boundary (--field-border) and placeholders read --placeholder (≥ 4.5:1), one global ::placeholder rule.'],
  'P4-COLOR-06': ['1', 'S', '--muted aliases --text-3, validated on wells and every paper as well as cards.'],
  'CONS-COLOR-1': ['1', 'S', 'Past, done and not-yet states use --text-2/--text-3 plus a glyph, never opacity on text.', 'Dimmed text fails contrast differently in each app.'],
  'CONS-COLOR-2': ['1', 'S', 'One today ring (--today-ring, ≥ 3:1) drawn one way.', 'Three today rings.'],
  'CONS-COLOR-3': ['1', 'S', 'Only --accent-ink (and --accent-on on a solid) become ink.', 'Four recipes turn the person colour into ink.'],
  'CONS-COLOR-4': ['1', 'S', 'Semantic families (success, warning, danger) with glyphs, ≥ 10 ΔE00 from every person colour (gated).', 'Semantic colours are inconsistent and ambiguous.'],
  'VIS-COLOR-1': ['1', 'M', 'The house pastels at full chroma for fills and tiles (pastel-to-saturated tile gradients), both missing hues added, dark cards lifted.', 'Fills sit at a third of the house chroma.'],
};
