// Phase 5 plan: the batches, in the order Phase 6 runs them (one commit each). Critical defects are pulled forward into
// the 0x batches (constitution: "Pull Critical bugs forward"); then batch 1 (design tokens, design.css, shared components),
// batch 2 (the hub shell), and one app per batch, ordered by daily use x gap size (computed in build-findings.mjs).
// Each batch lists the files it may touch, what it needs first, backups, and how it is verified.
export const BATCHES = {
  '0a': { title: 'The hub boots with Reduce Motion on', files: 'apps/hub.js, index.html', effort: 'S',
    why: 'Any family device with Reduce Motion on (iOS Settings → Accessibility → Motion) gets a blank page today, the pairing screen included. It is a one-line fix and has been live since 2026-09-17.',
    verify: ['node "audits/tools/phase2/VIS/verify-reduced-motion-blank-shell-2.mjs" (every Reduce Motion case must print shell.hidden=false)', 'node "audits/tools/phase2/VIS/density-motion.mjs" (last block)', 'scripts/test-design.mjs (reduced motion case)'] },
  '0b': { title: 'SDK: no write before the first load, safe migration, one household day', files: 'apps/hub.js; guards in each app that writes on open or on a tap (F260, Prayer, Tally, Timer, Kid Verse, Verses, Larder, both Dollywood exports via the sibling template)', effort: 'L',
    why: 'Ten critical data losses share one cause: hub.ready resolves before the app\'s own data has arrived (apps/hub.js:334-337), so a tap or an automatic save writes from an empty state over the real row. The same batch gives every app one "today" in New York time with a midnight event, because the apps disagree about the date today.',
    needs: [], backup: 'Export the production D1 (npx wrangler d1 export house-hub --remote --output …) before deploying; the batch changes no schema but guards writes to existing rows.',
    verify: ['each entry\'s reproduction script (listed per finding) must stop reproducing', 'node "audits/tools/phase2/SYNC/critic-done-during-stall.mjs" (the history must survive a held first pull)', 'capture rig loading states: node audits/tools/capture.mjs --state loading --out audits/screens-after/… (one folder per batch), then node audits/tools/lib/pxdiff.mjs against audits/screens', 'scripts/test-hub.mjs, test-f260.mjs, test-prayer.mjs, test-kidverse.mjs, test-rewards.mjs, test-verses.mjs, test-leftovers.mjs, test-timer.mjs'] },
  '0c': { title: 'SDK and shell: queued writes are never dropped, switching is clean', files: 'apps/hub.js, index.html, worker/src/data.js, worker/src/index.js', effort: 'L',
    why: 'Writes the device already accepted and showed are thrown away when an app closes, when the TV signs in, on "Forget this device", above 200 queued rows, or after a Switch; a fast clock reverts other people\'s edits; a pull in flight during Switch shows one person\'s private prayers to the next.',
    backup: 'Export the production D1 first (the Worker starts clamping future timestamps).',
    verify: ['each entry\'s reproduction script', 'node "audits/tools/phase2/SYNC/verify-batch-over-200-dropped-1.mjs"', 'scripts/test-hub.mjs (offline write → flush, kiosk read-only)', 'scripts/smoke-api.sh against the local Worker (120 checks)'] },
  '0d': { title: 'Security: accounts, private content, stored script, kid safety; the Kitchen device\'s server rules', files: 'worker/src/index.js, worker/src/auth.js, worker/src/data.js, worker/src/chat.js, worker/migrations/ (PIN claim, kitchen), worker/schema.sql, worker/seed.sql, scripts/smoke-api.sh and a new kitchen test in scripts/ (KITCHEN-1), CLAUDE.md, apps/hub.js, index.html, apps/prayer.html (escaping only; layout and ids stay), ../dollywood-build-project/scripts/template.html → both exports', effort: 'M',
    why: 'An account (the admin\'s included) can be taken over after any Reset PIN or by brute force with the pairing code; a guest name can run script in everyone\'s park map and replay the admin\'s tokens; private prayer titles reach the family feed and the TV; a guest can switch a child\'s location beacon. The Kitchen device\'s server rules (KITCHEN-1) belong here too: which kind may write what is a security rule.',
    backup: 'Export the production D1 before the migrations: the PIN claim (a table or column; per-profile rate-limit keys, additive) and the kitchen one (KITCHEN-1: an additive device role, and a rebuild of `profiles` to widen its kind CHECK). They take the next free numbers from 006.',
    verify: ['each entry\'s reproduction script (the XSS scripts must find no live node; the takeover and brute-force scripts must be refused)', 'scripts/smoke-api.sh (PIN flows, rate limits, admin 403s, guests, rally)', 'scripts/test-guests.mjs, test-prayer-faces.mjs', 'test-kitchen.mjs (new, KITCHEN-1)'] },
  '0e': { title: 'F260 and Verses: rows that cannot erase each other, a journal that cannot corrupt', files: 'apps/f260.html (data code only; layout and ids stay), apps/verses.html', effort: 'L',
    why: 'F260 is the household\'s original bug report ("progress not saving on the phone"). Whole-map rows let one device erase another\'s tick, a practice rating wipes the Verses schedule, and the encrypted journal can stop saving silently or become unreadable.',
    needs: ['0b', '0c'], backup: 'Export the production D1 first: the batch splits f260.done / f260.log / f260.recall into per-item rows (additive keys; the old map rows are kept read-only until every device has migrated).',
    verify: ['each entry\'s reproduction script', 'node "audits/tools/phase2/SYNC/verify-whole-map-lww-loses-ticks-1.mjs" and the P2-SYNC-19/-20 scripts', 'scripts/test-f260.mjs, test-verses.mjs, test-prefs.mjs', 'print check: the PDF route in audits/03-apps/f260.md (3 pages, 52 weeks)'] },
  '0f': { title: 'Tally and Kid Verse: counts and stars that add up across devices', files: 'apps/tally.html, apps/kidverse.html', effort: 'L',
    needs: ['0b', '0c'], backup: 'Export the production D1 first (stars and heard-days move to per-day rows; the mirror row is derived).',
    why: 'Two devices of one person lose each other\'s taps; a kid\'s second device erases a star or a heard day. These are the kids\' own records.',
    verify: ['each entry\'s reproduction script', 'scripts/test-rewards.mjs, test-kidverse.mjs, test-kidstory.mjs'] },
  '0g': { title: 'Prayer: no lost requests, notes or prayed days', files: 'apps/prayer.html (data code only; layout and ids stay)', effort: 'M',
    needs: ['0b'], backup: 'Export the production D1 first (ids of new rows change shape; existing rows keep theirs).',
    why: 'Prayer is the most-used app (every adult and both kids, daily). Two devices can pick the same id and lose a request, Import can erase other people\'s newer requests, "Put back on the list" erases the answer note, and an iPad left open past midnight files prayers under yesterday.',
    verify: ['each entry\'s reproduction script', 'node handoff/prayer/check.js apps/prayer.html (49 checks)', 'scripts/test-prayer.mjs, test-prayer-faces.mjs'] },
  '0h': { title: 'Larder and build guide: no one-tap loss', files: 'apps/leftovers.html, ../dollywood-build-project/scripts/template.html → apps/dollywood.html (+ the park map export)', effort: 'M',
    needs: ['0b'], why: 'A double-tap, a remote change under the finger or a kid\'s tap removes family food for everyone with no undo; the build guide\'s Import replaces all progress with any JSON file.',
    verify: ['each entry\'s reproduction script', 'scripts/test-leftovers.mjs, test-dollywood-sync.mjs; the sibling repo\'s verify.py before export'] },
  '0i': { title: 'Chat: writes that do what was asked, and say when they did not', files: 'worker/src/chat.js', effort: 'M',
    why: 'finish_leftover can remove a different food; a write that lost last-write-wins still shows ✓.',
    verify: ['each entry\'s reproduction script (scripted upstream via L.anthropic)', 'node scripts/mock-anthropic.mjs + scripts/smoke-chat.sh (39 checks)'] },
  '1': { title: 'Design tokens, design.css and shared components', files: 'apps/design.css (token half replaced by audits/tools/phase4/tokens/proposed-tokens.css; component half moved onto roles), apps/hub.js (theme, accent, preferences, bootstrap), a new additive migration, `<n>-profile-hue.sql` under worker/migrations/ (Phase 4 named it 006; batch 0d\'s migrations land first, so it takes the next free number), the tests that hard-code page colours; the Phase 4 batch-1a pre-pass rows in every app', effort: 'L',
    needs: ['the owner\'s approval of the rebuilt design preview (audits/05-decisions.md, "Before Phase 6 can start", item 5); the decisions themselves are answered'], backup: 'Export the production D1 before the profile-hue migration (additive column).',
    why: 'Most visual findings share causes in the token layer: mid-tone hues used as text, one light-theme hex per person, no iPad type tier, glass without Reduce Transparency, focus rings that vanish. Phase 4 measured them across 3,662 screen x theme x device jobs and proposed one verified token set.',
    verify: ['node audits/tools/phase4/tokens/contrast.mjs (0 failing) and browser-check.mjs', 'the measurement rig after the change: node audits/tools/phase4/measure.mjs --run themes|devices|states --out … then aggregate.mjs, compared with the committed audits/evidence/p4/measure/*.json', 'capture rig, all areas: node audits/tools/capture.mjs --out audits/screens-after/… (one folder per batch), then pxdiff against audits/screens', 'scripts/test-design.mjs, screens-themes.mjs, screens-apps.mjs, screens-shell.mjs, test-prefs.mjs', 'rescore the rubric for every row (the Phase 4 scorecard method)'] },
  '2a': { title: 'Hub shell: Home, Apps, Me, Chat, profiles; the Kitchen device', files: 'index.html, apps/hub.js; for the Kitchen face sheet (KITCHEN-2), the calls in apps/prayer.html (data code only; layout and ids stay) and apps/leftovers.html, the kitchen test\'s UI half, CLAUDE.md', effort: 'L', needs: ['1', '0d (KITCHEN-1)'],
    why: 'The shell is what every household member sees first, many times a day, on the always-on Kitchen iPad.',
    verify: ['each entry\'s reproduction script', 'capture rig: --area shell --out audits/screens-after/… + pxdiff', 'scripts/test-hub.mjs, test-home.mjs, test-apps.mjs, test-guests.mjs, test-photos.mjs, test-timer.mjs, test-kitchen.mjs, screens-shell.mjs'] },
  '2b': { title: 'Worker: push, reminders, chat and PWA', files: 'worker/src/*.js, sw.js, manifest.json, index.html (push and install UI)', effort: 'M', needs: ['0c'],
    why: 'Reminders and pushes are how the hub reaches people who are not looking at it.',
    verify: ['each entry\'s reproduction script', 'scripts/test-push.mjs, test-push2.mjs (with scripts/push-receiver.mjs), smoke-chat.sh, smoke-api.sh', 'node scripts/bump-sw.mjs --check'] },
  '2c': { title: 'The TV board', files: 'index.html (the .tv grid), apps/design.css (kiosk tier)', effort: 'M', needs: ['1'],
    why: 'The downstairs TV runs 24/7 and is read from the sofa; today it hides reminders and uses phone-sized text.',
    verify: ['scripts/test-tv.mjs (200 crossfades, constant nodes, fits 1920x1080)', 'capture rig: --area tv --out audits/screens-after/… + pxdiff', 'audits/tools/phase4/tokens/rev2-runtime.mjs fit check with data-tv-scale="10ft"'] },
};
// App batches: one app per batch (constitution). Order: the household's answer (audits/05-decisions.md, "App batch order"),
// which confirmed the order computed from daily use x gap; build-findings.mjs keeps it and says if the scores ever disagree.
export const APP_ORDER = ['prayer', 'f260', 'verses', 'timer', 'kidverse', 'leftovers', 'dollywood', 'dollywood-live', 'tally'];
// use = estimated household sessions per day, from each app's jobs table in audits/03-apps/<id>.md §1 (no usage data exists).
export const APPS = {
  prayer: { name: 'Prayer', use: 7, useWhy: 'every adult daily plus Ezra and Kiara daily (prayer.md §1)', files: 'apps/prayer.html (restyle through tokens only; layout and ids stay)' },
  f260: { name: 'F260 Reading Plan', use: 4, useWhy: 'four adult readers, daily (f260.md §1)', files: 'apps/f260.html (restyle through tokens only; layout and ids stay)' },
  verses: { name: 'Verses', use: 4, useWhy: 'four adults daily, kids a few times a week (verses.md §1)', files: 'apps/verses.html' },
  timer: { name: 'Kitchen timer', use: 3, useWhy: 'several times a day around meals (timer.md §1)', files: 'apps/timer.html, index.html (timer pill)' },
  leftovers: { name: 'Larder Ledger', use: 2, useWhy: 'about one log and one finish a day in the app; the Home card carries the glances (leftovers.md §1)', files: 'apps/leftovers.html' },
  kidverse: { name: 'Kid Verse', use: 2, useWhy: 'both kids daily (kidverse.md §1)', files: 'apps/kidverse.html' },
  tally: { name: 'Tally counter', use: 0.5, useWhy: 'occasional bursts (tally.md §1)', files: 'apps/tally.html' },
  dollywood: { name: 'Dollywood build guide', use: 0.4, useWhy: 'Eli, a few build sessions a week (dollywood.md §1)', files: '../dollywood-build-project/scripts/template.html → apps/dollywood.html' },
  'dollywood-live': { name: 'Dollywood park map', use: 0.2, useWhy: 'park days only, then heavily (dollywood-live.md §1)', files: '../dollywood-build-project/scripts/template.html → apps/dollywood-live.html' },
};
export const APP_TESTS = {
  prayer: 'node handoff/prayer/check.js apps/prayer.html; scripts/test-prayer.mjs, test-prayer-faces.mjs', f260: 'scripts/test-f260.mjs, test-prefs.mjs, test-kidstory.mjs; the PDF print check',
  verses: 'scripts/test-verses.mjs', timer: 'scripts/test-timer.mjs', leftovers: 'scripts/test-leftovers.mjs', kidverse: 'scripts/test-kidverse.mjs, test-rewards.mjs, test-kidstory.mjs',
  tally: 'scripts/test-apps.mjs (Tally cases)', dollywood: 'scripts/test-dollywood-sync.mjs; the sibling repo\'s verify.py', 'dollywood-live': 'scripts/smoke-api.sh (waits, rally); the sibling repo\'s verify.py',
};
// Step 4 (audits/05-decisions.md, "Before Phase 6 can start" item 4): work the household's answers add, which no Phase 2-4
// finding filed. build-findings.mjs renders each at the top of its batch, apart from the finding counts. A finding the work
// makes moot says so in its own fix (P2-PROF-09 in fixes-shell.mjs).
export const WORK = [
  { id: 'KITCHEN-1', batch: '0d', effort: 'M', title: 'Kitchen device, data and server half: a device role, a kitchen profile kind, and server rules for what a kitchen session may write',
    src: 'audits/05-decisions.md:42',
    code: ['worker/schema.sql:9', 'worker/src/auth.js:110', 'worker/src/index.js:231', 'worker/src/index.js:470'],
    now: "The only shared kinds are adult, kid and kiosk (`worker/schema.sql:9`); the kiosk cannot write at all (`worker/src/auth.js:110`), so the Kitchen iPad today is signed in as a person, and whoever picks it up inherits that person (P2-PROF-09). A paired device has no role (the `devices` table in `worker/schema.sql`), and `POST /api/login` lets any paired device sign in as any profile (`worker/src/index.js:231`).",
    why: "The household chose a shared Kitchen mode for the counter iPad instead of an idle return (P5-D5 as answered): family apps with no personal sign-ins. Only the server can make that hold; a client-only mode is one crafted request away from a personal session.",
    fix: [
      "A migration, with the D1 export first: `devices.role` (NULL or `'kitchen'`, `ADD COLUMN`, additive), and `'kitchen'` added to the profile kinds, plus one seeded kitchen profile. SQLite cannot alter a CHECK constraint, so widening `kind IN ('adult','kid','kiosk')` (`worker/schema.sql:9`) means SQLite's table rebuild of `profiles` (new table, copy, drop, rename, in one batch). It is the plan's one non-additive schema step; it is checked by row counts and a column-by-column compare before and after, and `schema.sql` follows. `sessions.profile_id` has no foreign key, so sessions survive it.",
      "Login: a device whose role is kitchen can sign in only as the kitchen profile, with no PIN; the kitchen profile can sign in only from such a device (`worker/src/index.js:231`). Nobody picks a person there.",
      "Writes: a kitchen session may write family scope (Larder, the family prayer list, family reminders, the album), and person scope only under its own profile id and only for Timer and Tally, which store `scope: person` today (`apps.json`), until batch 6's family timers channel (GAP-HOME-1). It can read no one's person scope. Chat and admin refuse it, as they refuse the kiosk (`worker/src/chat.js:391`, `requireAdmin` in `worker/src/auth.js`); push subscription refuses it too, a new rule, since today it checks only for a profile (`worker/src/index.js:410-412`).",
      "The kitchen profile is not a person: `GET /api/profiles` marks it so every picker leaves it out (the server refuses its sign-in there anyway), `hub.people()` and the face sheet skip it, the admin's Reset PIN refuses it, and Edit accepts only its colour (the admin assigns every profile's colour, `audits/05-decisions.md`, \"Admin-assigned colours\"), not its name, kind or PIN.",
      "The device learns its role: `GET /api/device` (device token only) returns `{ role }`. The shell asks at boot and after any 401; on a kitchen device it signs in as the kitchen profile instead of showing the picker. So a device whose role is set while it holds a personal session moves to the kitchen on its next request.",
      "Attribution: a write from a kitchen session that credits someone (a name added to a family prayer's `prayedBy[date]`, `apps/prayer.html:1599-1601`; the person an activity line such as \"Finished the soup\" is filed under, `apps/leftovers.html:308-309`, which the Worker today takes from the session; the `by` of an album photo, `worker/src/index.js:361-369`, where only adults may add today) must name a household profile (not a guest, not the kitchen or the TV); the Worker checks it against `profiles` and refuses anything else, and refuses a kid named on a Larder write (P5-D2: kids are read-only there). Kid Verse's prayer credit already reads those names (`apps/kidverse.html:426-430`), so a kid who taps their face earns that day's prayer star with no Kid Verse change.",
      "Role changes: `PUT /api/admin/devices/:id/role`, from the admin's own session on another device, with a fresh admin PIN check. Setting kitchen ends that device's other sessions; clearing it ends the device's kitchen session, and the Worker also refuses a kitchen session on any request from a device that is no longer a kitchen. So the next request gets a 401, `GET /api/device` answers no role, and the shell shows the picker. The admin's kind editor (`worker/src/index.js:470`) does not offer kitchen: a profile becomes the kitchen only through the seed.",
      "CLAUDE.md in the same commit: the kitchen profile in \"Profiles\", the kitchen rules in \"How the hub works\", and `test-kitchen.mjs` in the Tests table.",
    ],
    verify: ["a new kitchen test, `test-kitchen.mjs` in the repo scripts folder, in the style of `test-hub.mjs`: the kitchen device writes family data; it cannot read or write any person's scope; it cannot sign in as a person, and no other device can sign in as the kitchen; a face tap on Prayed credits the tapped person (Ezra's prayer star appears after Kid Verse opens); a name outside the household is refused",
      "new `scripts/smoke-api.sh` cases: the role endpoint is admin only and needs the PIN; kitchen chat, push and admin calls get 403; the kitchen is absent from `GET /api/profiles`' picker list; a kid named on a Larder write is refused; after the role is cleared, the old kitchen session gets 401",
      "the migration on a copy of the production export: same row count and same values in every `profiles` column before and after"] },
  { id: 'KITCHEN-2', batch: '2a', effort: 'M', title: 'Kitchen device, shell half: no picker, no Me tab, the family apps only, and a face-tap sheet for credit',
    src: 'audits/05-decisions.md:42',
    code: ['index.html:478-481', 'index.html:1704-1706', 'apps/prayer.html:1599-1601', 'worker/src/index.js:549'],
    now: "A paired device with no stored session opens on the profile picker (`index.html:1704-1706`), and Switch returns any device to it; the Apps list is per person, with the kiosk seeing none (`index.html:478-481`). An action that credits someone credits the signed-in person: Prayed adds `hub.profile.name` (`apps/prayer.html:1599-1601`). Admin → Devices can only unpair (`worker/src/index.js:549`).",
    why: "This is what the family sees on the counter iPad all day. It replaces the idle return that P2-PROF-09 proposed: with no personal sign-in on the Kitchen iPad, there is nothing to time out.",
    fix: [
      "A kitchen device never shows the picker: at boot and after any 401 the shell asks `GET /api/device` (KITCHEN-1) and, on a kitchen device, signs in as the kitchen. It opens on a kitchen Home (the calm, glanceable layout of UX-HOME-1: the running timer, food to eat soon, today's family prayers, reminders) with no Me tab and no Chat tab.",
      "Its Apps list is fixed: Larder, Prayer (the family list only, adult-sized: no private lists), Timer and Tally. `visibleApps` gets a kitchen branch next to the kiosk's (`index.html:478-481`). The family album is a Home card with an Add button.",
      "`hub.whoDidThis()`: a sheet with a row of the household's faces, no PIN, returning the chosen profile. Prayer's Prayed shows everyone in the household, kids included; the Larder's finish and the album's Add show the adults only (P5-D2; the album admits adults today). They send the chosen person instead of `hub.profile`. It is attribution, not a sign-in: nothing else changes hands. Prayer changes only in data code (its layout and ids stay, CLAUDE.md); the sheet is the SDK's overlay.",
      "Admin → Devices gains \"Kitchen\" per device, set and cleared only from the admin panel on Eli's own devices, confirmed with the admin PIN (KITCHEN-1's endpoint). The kitchen device itself has no way in to admin, as the decision says.",
      "CLAUDE.md in the same commit: the kitchen shell in \"How the hub works\" and the kitchen device in \"Admin operations\".",
    ],
    verify: ["`test-kitchen.mjs` (UI half): no picker and no Me or Chat tab at 390, 820 and 1280; only the four apps; Prayed, finish and the album's Add open the face sheet, and the chosen person shows on another device's list and in the feed; the Larder's sheet has no kids; the kitchen is in no other device's picker; the role set while the iPad holds Eli's session moves it to the kitchen Home on its next request, with no picker; clearing the role puts it on the picker on its next request, and it can no longer act as the kitchen; setting and clearing the role from Admin → Devices refuses a wrong PIN",
      "capture rig: a kitchen state for the shell area (`--area shell`), into the batch 2a after-run folder"] },
];
// Items the household cut (audits/05-decisions.md, "Features kept or cut"): not planned; listed under "What this report does not list".
export const CUT = {
  'GAP-DOLLYWOOD-2': '**Cut:**',   // text on the 05-decisions.md line that records it; build-findings.mjs cites that line
};
