// Phase 5 plan: the batches, in the order Phase 6 runs them (one commit each). Critical defects are pulled forward into
// the 0x batches (constitution: "Pull Critical bugs forward"); then batch 1 (design tokens, design.css, shared components),
// batch 2 (the hub shell), and one app per batch, ordered by daily use x gap size (computed in build-findings.mjs).
// Each batch lists the files it may touch, what it needs first, backups, and how it is verified.
export const BATCHES = {
  '0a': { title: 'The hub boots with Reduce Motion on', files: 'apps/hub.js, index.html', effort: 'S',
    why: 'Any family device with Reduce Motion on (iOS Settings → Accessibility → Motion) gets a blank page today, the pairing screen included. It is a one-line fix and has been live since 2026-09-17.',
    verify: ['node "audits/tools/phase2/VIS/verify-reduced-motion-blank-shell-2.mjs" (every Reduce Motion case must print shell.hidden=false)', 'node "audits/tools/phase2/VIS/density-motion.mjs" (last block)', 'scripts/test-design.mjs (reduced motion case)'] },
  '0b': { title: 'SDK: no write before the first load, safe migration, one household day', files: 'apps/hub.js; guards in each app that writes on open or on a tap (F260, Prayer, Tally, Timer, Kid Verse, Verses, Larder, both Dollywood exports via the sibling template)', effort: 'L',
    why: 'Ten critical data losses share one cause: hub.ready resolves before the app\'s own data has arrived (apps/hub.js:334-337), so a tap or an automatic save writes from an empty state over the real row. The same batch gives every app one "today" in New York time with a midnight event, because the apps disagree about the date today.',
    needs: [], backup: 'Export the production D1 (npx wrangler d1 export house-hub --remote --output …) before deploying; the batch changes no schema but guards writes to existing rows.',
    verify: ['each entry\'s reproduction script (listed per finding) must stop reproducing', 'node "audits/tools/phase2/SYNC/critic-done-during-stall.mjs" (the history must survive a held first pull)', 'capture rig loading states: node audits/tools/capture.mjs --state loading --out audits/screens-after/… (one folder per batch), then node audits/tools/lib/pxdiff.mjs against audits/screens', 'scripts/test-hub.mjs, test-f260.mjs, test-prayer.mjs, test-kidverse.mjs, test-rewards.mjs, test-verses.mjs, test-leftovers.mjs, test-timer.mjs'] },
  '0c': { title: 'SDK and shell: queued writes are never dropped, switching is clean', files: 'apps/hub.js, index.html, worker/src/data.js, worker/src/index.js', effort: 'L',
    why: 'Writes the device already accepted and showed are thrown away when an app closes, when the TV signs in, on "Forget this device", above 200 queued rows, or after a Switch; a fast clock reverts other people\'s edits; a pull in flight during Switch shows one person\'s private prayers to the next.',
    backup: 'Export the production D1 first (the Worker starts clamping future timestamps).',
    verify: ['each entry\'s reproduction script', 'node "audits/tools/phase2/SYNC/verify-batch-over-200-dropped-1.mjs"', 'scripts/test-hub.mjs (offline write → flush, kiosk read-only)', 'scripts/smoke-api.sh against the local Worker (120 checks)'] },
  '0d': { title: 'Security: accounts, private content, stored script, kid safety', files: 'worker/src/index.js, worker/src/auth.js, worker/src/data.js, worker/src/chat.js, apps/hub.js, index.html, apps/prayer.html (escaping only; layout and ids stay), ../dollywood-build-project/scripts/template.html → both exports', effort: 'M',
    why: 'An account (the admin\'s included) can be taken over after any Reset PIN or by brute force with the pairing code; a guest name can run script in everyone\'s park map and replay the admin\'s tokens; private prayer titles reach the family feed and the TV; a guest can switch a child\'s location beacon.',
    backup: 'Export the production D1 before the additive migration (a PIN-claim table or column; per-profile rate-limit keys).',
    verify: ['each entry\'s reproduction script (the XSS scripts must find no live node; the takeover and brute-force scripts must be refused)', 'scripts/smoke-api.sh (PIN flows, rate limits, admin 403s, guests, rally)', 'scripts/test-guests.mjs, test-prayer-faces.mjs'] },
  '0e': { title: 'F260 and Verses: rows that cannot erase each other, a journal that cannot corrupt', files: 'apps/f260.html (data code only; layout and ids stay), apps/verses.html', effort: 'L',
    why: 'F260 is the household\'s original bug report ("progress not saving on the phone"). Whole-map rows let one device erase another\'s tick, a practice rating wipes the Verses schedule, and the encrypted journal can stop saving silently or become unreadable.',
    needs: ['0b', '0c'], backup: 'Export the production D1 first: the batch splits f260.done / f260.log / f260.recall into per-item rows (additive keys; the old map rows are kept read-only until every device has migrated).',
    verify: ['each entry\'s reproduction script', 'node "audits/tools/phase2/SYNC/verify-whole-map-lww-loses-ticks-1.mjs" and the P2-SYNC-19/-20 scripts', 'scripts/test-f260.mjs, test-verses.mjs, test-prefs.mjs', 'print check: the PDF route in audits/03-apps/f260.md (3 pages, 52 weeks)'] },
  '0f': { title: 'Tally and Kid Verse: counts and stars that add up across devices', files: 'apps/tally.html, apps/kidverse.html', effort: 'L',
    needs: ['0b', '0c'], backup: 'Export the production D1 first (stars and heard-days move to per-day rows; the mirror row is derived).',
    why: 'Two devices of one person lose each other\'s taps; a kid\'s second device erases a star or a heard day. These are the kids\' own records.',
    verify: ['each entry\'s reproduction script', 'scripts/test-rewards.mjs, test-kidverse.mjs, test-kidstory.mjs'] },
  '0g': { title: 'Prayer: no lost requests, notes or prayed days', files: 'apps/prayer.html (data code only; layout and ids stay)', effort: 'M',
    needs: ['0b'], backup: 'Export the production D1 first (ids of new rows change shape; existing rows keep theirs).',
    why: 'Prayer is the most-used app (every adult and both kids, daily). Two devices can pick the same id and lose a request, Import can erase other people\'s newer requests, "Put back on the list" erases the answer note, and an iPad left open past midnight files prayers under yesterday.',
    verify: ['each entry\'s reproduction script', 'node handoff/prayer/check.js apps/prayer.html (49 checks)', 'scripts/test-prayer.mjs, test-prayer-faces.mjs'] },
  '0h': { title: 'Larder and build guide: no one-tap loss', files: 'apps/leftovers.html, ../dollywood-build-project/scripts/template.html → apps/dollywood.html (+ the park map export)', effort: 'M',
    needs: ['0b'], why: 'A double-tap, a remote change under the finger or a kid\'s tap removes family food for everyone with no undo; the build guide\'s Import replaces all progress with any JSON file.',
    verify: ['each entry\'s reproduction script', 'scripts/test-leftovers.mjs, test-dollywood-sync.mjs; the sibling repo\'s verify.py before export'] },
  '0i': { title: 'Chat: writes that do what was asked, and say when they did not', files: 'worker/src/chat.js', effort: 'M',
    why: 'finish_leftover can remove a different food; a write that lost last-write-wins still shows ✓.',
    verify: ['each entry\'s reproduction script (scripted upstream via L.anthropic)', 'node scripts/mock-anthropic.mjs + scripts/smoke-chat.sh (39 checks)'] },
  '1': { title: 'Design tokens, design.css and shared components', files: 'apps/design.css (token half replaced by audits/tools/phase4/tokens/proposed-tokens.css; component half moved onto roles), apps/hub.js (theme, accent, preferences, bootstrap), a new additive migration, 006-profile-hue.sql, under worker/migrations/, the tests that hard-code page colours; the Phase 4 batch-1a pre-pass rows in every app', effort: 'L',
    needs: ['the household\'s decisions D1-D18 and P5-D1-P5-D9 (below)'], backup: 'Export the production D1 before 006-profile-hue.sql (additive column).',
    why: 'Most visual findings share causes in the token layer: mid-tone hues used as text, one light-theme hex per person, no iPad type tier, glass without Reduce Transparency, focus rings that vanish. Phase 4 measured them across 3,662 screen x theme x device jobs and proposed one verified token set.',
    verify: ['node audits/tools/phase4/tokens/contrast.mjs (0 failing) and browser-check.mjs', 'the measurement rig after the change: node audits/tools/phase4/measure.mjs --run themes|devices|states --out … then aggregate.mjs, compared with the committed audits/evidence/p4/measure/*.json', 'capture rig, all areas: node audits/tools/capture.mjs --out audits/screens-after/… (one folder per batch), then pxdiff against audits/screens', 'scripts/test-design.mjs, screens-themes.mjs, screens-apps.mjs, screens-shell.mjs, test-prefs.mjs', 'rescore the rubric for every row (the Phase 4 scorecard method)'] },
  '2a': { title: 'Hub shell: Home, Apps, Me, Chat, profiles', files: 'index.html, apps/hub.js', effort: 'L', needs: ['1'],
    why: 'The shell is what every household member sees first, many times a day, on the always-on Kitchen iPad.',
    verify: ['each entry\'s reproduction script', 'capture rig: --area shell --out audits/screens-after/… + pxdiff', 'scripts/test-hub.mjs, test-home.mjs, test-apps.mjs, test-guests.mjs, test-photos.mjs, test-timer.mjs, screens-shell.mjs'] },
  '2b': { title: 'Worker: push, reminders, chat and PWA', files: 'worker/src/*.js, sw.js, manifest.json, index.html (push and install UI)', effort: 'M', needs: ['0c'],
    why: 'Reminders and pushes are how the hub reaches people who are not looking at it.',
    verify: ['each entry\'s reproduction script', 'scripts/test-push.mjs, test-push2.mjs (with scripts/push-receiver.mjs), smoke-chat.sh, smoke-api.sh', 'node scripts/bump-sw.mjs --check'] },
  '2c': { title: 'The TV board', files: 'index.html (the .tv grid), apps/design.css (kiosk tier)', effort: 'M', needs: ['1'],
    why: 'The downstairs TV runs 24/7 and is read from the sofa; today it hides reminders and uses phone-sized text.',
    verify: ['scripts/test-tv.mjs (200 crossfades, constant nodes, fits 1920x1080)', 'capture rig: --area tv --out audits/screens-after/… + pxdiff', 'audits/tools/phase4/tokens/rev2-runtime.mjs fit check with data-tv-scale="10ft"'] },
};
// App batches: one app per batch (constitution). Order: the household's answer (audits/05-decisions.md, "App batch order"),
// which confirmed the order computed from daily use x gap; build-findings.mjs keeps it and says if the scores ever disagree.
export const APP_ORDER = ['prayer', 'f260', 'verses', 'timer', 'kidverse', 'leftovers', 'dollywood', 'dollywood-live', 'tally'];
// use = estimated household sessions per day, from each app's jobs table in audits/03-apps/<id>.md §1 (no usage data exists).
export const APPS = {
  prayer: { name: 'Prayer', use: 7, useWhy: 'every adult daily plus Ezra and Kiara daily (prayer.md §1)', files: 'apps/prayer.html (restyle through tokens only; layout and ids stay)' },
  f260: { name: 'F260 Reading Plan', use: 4, useWhy: 'four adult readers, daily (f260.md §1)', files: 'apps/f260.html (restyle through tokens only; layout and ids stay)' },
  verses: { name: 'Verses', use: 4, useWhy: 'four adults daily, kids a few times a week (verses.md §1)', files: 'apps/verses.html' },
  timer: { name: 'Kitchen timer', use: 3, useWhy: 'several times a day around meals (timer.md §1)', files: 'apps/timer.html, index.html (timer pill)' },
  leftovers: { name: 'Larder Ledger', use: 2, useWhy: 'about one log and one finish a day in the app; the Home card carries the glances (leftovers.md §1)', files: 'apps/leftovers.html' },
  kidverse: { name: 'Kid Verse', use: 2, useWhy: 'both kids daily (kidverse.md §1)', files: 'apps/kidverse.html' },
  tally: { name: 'Tally counter', use: 0.5, useWhy: 'occasional bursts (tally.md §1)', files: 'apps/tally.html' },
  dollywood: { name: 'Dollywood build guide', use: 0.4, useWhy: 'Eli, a few build sessions a week (dollywood.md §1)', files: '../dollywood-build-project/scripts/template.html → apps/dollywood.html' },
  'dollywood-live': { name: 'Dollywood park map', use: 0.2, useWhy: 'park days only, then heavily (dollywood-live.md §1)', files: '../dollywood-build-project/scripts/template.html → apps/dollywood-live.html' },
};
export const APP_TESTS = {
  prayer: 'node handoff/prayer/check.js apps/prayer.html; scripts/test-prayer.mjs, test-prayer-faces.mjs', f260: 'scripts/test-f260.mjs, test-prefs.mjs, test-kidstory.mjs; the PDF print check',
  verses: 'scripts/test-verses.mjs', timer: 'scripts/test-timer.mjs', leftovers: 'scripts/test-leftovers.mjs', kidverse: 'scripts/test-kidverse.mjs, test-rewards.mjs, test-kidstory.mjs',
  tally: 'scripts/test-apps.mjs (Tally cases)', dollywood: 'scripts/test-dollywood-sync.mjs; the sibling repo\'s verify.py', 'dollywood-live': 'scripts/smoke-api.sh (waits, rally); the sibling repo\'s verify.py',
};
