// Phase 6: the status of every finding a batch has closed, read by audits/tools/phase5/build-findings.mjs so that
// audits/05-findings.md carries it (constitution, Phase 6: "Update audits/05-findings.md with status (FIXED / PARTIAL /
// DEFERRED / NEEDS DEVICE CHECK) and the commit hash"). One entry per finding; a pointer gets its primary's status.
// The batch's full record (reruns, captures, tests, what was not verified) is in audits/06-implementation.md.
//
// BATCHES[n]: the batch's code commit and date.
// STATUS[id]: { status, batch, note, after: [after-evidence paths] }. The commit comes from the batch.

export const STATUSES = ['FIXED', 'PARTIAL', 'DEFERRED', 'NEEDS DEVICE CHECK'];

export const BATCHES = {
  '0a': { commit: 'ae274a6', date: '2026-09-26' },
  '0b': { commit: 'd968db8', date: '2026-09-26' },
  '0c': { commit: 'e9e5f59', date: '2026-09-26' },
};

// Batch 0b after-evidence lives under audits/evidence/p6/0b/ (the Phase 2/3 scripts' outputs, moved there from p2/p3 so the
// baseline stays as it was, plus the new checks in audits/tools/phase6/0b/). E = that folder.
const E = 'audits/evidence/p6/0b/';
const B0 = (id, note, after, status = 'FIXED') => [id, { status, batch: '0b', note, after: after.map(p => p.startsWith('audits/') ? p : E + p) }];
const S0b = [
  B0('P2-SYNC-02', 'hub.ready waits on the app\'s own channels (hub.isLoaded) and hub.set refuses an unloaded channel; Prayer loads, saves and migrates only after its person and family channels have pulled. Ezra\'s first open: server rows CHANGED {} (was prayerDays 29→0, plans replaced); family keys POSTed on first open [].', ['p2/SYNC/verify-ready-seen-ezra-real.json', 'p2/SYNC/e8-ready-seen.json']),
  B0('P2-SYNC-03', 'hub.migrate is async: it waits for the scope to load and a fresh successful pull, then writes only keys the server lacks, never for guests. e2h: server done 187 / week 38 kept, migrated mark set; verify-1 arms A-G all "overwritten = false" (failed-pull arms stay on the loading state and migrate nothing).', ['p2/SYNC/e2h-migrate-race.json', 'p2/SYNC/verify-migrate-race-overwrites-history-1.json']),
  B0('P2-SYNC-05', 'F260 writes weekStart only when a week really starts (first tick or setCurrent), never on open. e2d: no POSTs during the held pull, weekStart 38 weeks kept; verify-2: all five variants "intact".', ['p2/SYNC/e2d-slow-first-pull.json', 'p2/SYNC/verify2-slow-first-pull.json', 'p2/SYNC/e2d-phone-f260-at-7s.png']),
  B0('P2-SYNC-17', 'Done is disabled "Loading your progress…" until the f260 channel has pulled. critic-done-during-stall: at 7 s Done read "Loading your progress…", the tap landed after the data: done 187→188, log 169→170 (was wiped). verify2-2 A-D all 188/170, weekStart intact; verify2-1\'s stall arm now times out on the disabled Done (the fix holding), and f260-loading.mjs shows a forced tap during the hold POSTs nothing.', ['p2/SYNC/critic-done-during-stall.json', 'p2/SYNC/verify2-done-during-stalled-pull-2.json', 'f260-loading.json', 'f260-loading-held-iphone.png']),
  B0('P3-KIDVERSE-01', 'Done ★ is disabled "Getting your stars…" until both kidverse scopes have pulled; award() and reconcile() run only when loaded. verify-award-1/2: slow, fail, outage, latency and blip arms leave total/earned/badges/payouts intact and add exactly one star after load; kidverse-first-load A: direct award() returns false with 0 POSTs.', ['p3/kidverse/verify-award-first-pull-wipes-stars-1.json', 'p3/kidverse/verify-award-first-pull-wipes-stars-2.json', 'kidverse-first-load-A-outage.png', 'kidverse-first-load-A-after.png']),
  B0('P3-KIDVERSE-03', 'The adult week stepper is disabled ("Loading the family week…") until the family scope has pulled. verify-week-stepper-1: the tap stepped the real week 38→39, not 1→2; -2\'s fail arm now times out on the disabled + (the fix holding); kidverse-first-load B: setWeek(2) sends 0 POSTs, server keeps week 38.', ['p3/kidverse/verify-week-stepper-stalled-overwrite-1.json', 'p3/kidverse/adult-week.json', 'kidverse-first-load-B-outage.png']),
  B0('P3-KIDVERSE-11', '"I heard it" is disabled "Getting your story…" until the story rows have pulled. All three heard scripts: earlier heard days survive ("Heard 2 days this week").', ['p3/kidverse/critic-heard-first2.json', 'p3/kidverse/verify-critic-heard-first-load-overwrites-story-row-3-1.json', 'p3/kidverse/verify-critic-heard-first-load-overwrites-story-row-3-2.json']),
  B0('P3-PRAYER-02', 'Prayer paints a loading state and writes nothing until its channels have pulled. slow-start hold9s: first paint "Loading your prayer list…", posts [], prayerDays 41 and plans unchanged (was 8+6 keys POSTed, 41→0); verify-1/2 latency, fail503, hold9s and network-error arms: no wipe.', ['p3/prayer/slow-start.json', 'p3/prayer/verify-slow-start-person-wipe-1.json', 'p3/prayer/verify-slow-start-person-wipe-2.json', 'p3/prayer/slow-start-hold9s-first-paint.png']),
  B0('P3-TALLY-02', '+, − and Reset are disabled (aria-busy) until the count has arrived. first-load hold/fail: shownAtReady "", the tap lands after load on the real count 37→38 (was 37→1); kid 12→13; tally-loading.mjs: forced taps at 2 s change nothing and send nothing.', ['p3/tally/first-load.json', 'p3/tally/verify-first-load-tap-overwrites-count-2.json', 'tally-loading-hold-light.png', 'tally-loading-fail-dark.png']),
  B0('P3-VERSES-03', 'No rating until the verses and f260 channels (and kidverse family for kids) have pulled: Show and the ratings are disabled on a skeleton card. verify-first-open-1 slow/control and -2 latency: server log 13→14 days (was cut to 1); the offline and kid arms now time out on the disabled Show (the fix holding); verses-first-open.mjs A/B: offline and cold-kid taps queue nothing.', ['p3/verses/verify-first-open-wipes-log-1-slow-result.json', 'p3/verses/verify-first-open-wipes-log-2-latency.json', 'verses-A-offline-loading-iphone.png', 'verses-B-kid-cold-loading-iphone.png']),
  B0('P2-HOME-02', 'F260\'s summary carries readOn; Home computes "read today" and the streak from the synced f260.log for today\'s New York date (F260\'s own streak rule), chat\'s f260_status reads the log too, and the 8 pm job already did. verify-stale-1: Tue "reading done · read today ✓"; Wed "a reading waiting" (was "reading done"); Sat, 3 unread days later, no streak.', ['p2/HOME/verify-stale-1.json', 'p2/HOME/verify-stale-2.json']),
  B0('P2-STAB-07', 'F260 and Kid Verse re-render on hub.onDay (and on visibility when the day changed); the shell re-renders Home at the household midnight. midnight.mjs: F260 rolls to "TODAY / Mon, Sep 28"; Kid Verse drops last week\'s stars and rings Monday; the kid Home card goes from 3 stars to "No stars yet".', ['p2/STAB/midnight.json', 'p2/STAB/midnight-tue.json']),
  B0('P3-LEFTOVERS-03', 'Ages are hub.daysBetween(dateLogged, hub.today()) in the Larder and on Home. verify-dst-1/2 and dates: ages equal calendar days across spring-forward and fall-back.', ['p3/leftovers/verify-dst-spring-forward-off-by-one-1.json', 'p3/leftovers/verify-dst-spring-forward-off-by-one-2.json', 'p3/leftovers/dates-dst.json']),
  B0('P3-TALLY-06', 'hub.profile.isGuest now reaches the SDK and hub.migrate skips guests without marking the scope. critic-guest-migrate: the guest sees 0, no mark, no server row; Mom then gets 23.', ['p3/tally/critic-guest-migrate.json', 'p3/tally/verify-critic-guest-gets-legacy-migration-2-2.json']),
  B0('P3-TALLY-07', 'A skeleton pill replaces the markup\'s placeholder 0 until the count arrives. fake-zero-5-1/5-2: in every hold, fail and abort sample the dial is empty with + disabled and aria-busy, then the real 37; no 0 is ever painted.', ['p3/tally/verify-critic-fake-zero-while-loading-5-1.json', 'p3/tally/verify-critic-fake-zero-while-loading-5-2.json', 'tally-loading-hold-light.png']),
  B0('P3-TIMER-01', 'Start, Reset and the presets stay disabled on a skeleton dial until this page\'s own timer pull has succeeded, the device is truly offline with a pulled cache, or the server has been unreachable for 8 s with a pulled cache. verify-slowload-1: hold9, lat8, fail and ctrl all replaced:false; timer-stale-taps: forced taps change nothing in the warm, cold and fail arms, and offline with a warm cache Start works and queues timer.active.', ['p3/timer/verify-slowload-start-replaces-running-timer-1.json', 'timer-stale-taps-warm-loading.png', 'timer-stale-taps-offwarm-started.png']),
  B0('P3-VERSES-04', 'Verses re-renders on hub.onDay. midnight and verify-midnight-1/2: at 00:05 Eli goes from "All done for today" to "9 to go" and Ezra from "Come back tomorrow!" to "2 to go".', ['p3/verses/midnight.json', 'p3/verses/verify-midnight-stale-all-done-1.json', 'p3/verses/midnight-eli-ipad-after.png']),
  B0('UX-DOLLYWOOD-5', 'The build guide (template, rebuilt and exported) shows "Loading your progress…", chips without counts and a disabled Mark done / Next unfinished until the person scope has pulled. data-checks L1: during load "Loading your progress…", markDone.disabled true; after load "7 of 9 done"; L2: a tick during load changes nothing (server stays 24).', ['p3/dollywood/data-checks-L1-L2.json', 'p3/dollywood/first-open-loading.png']),
  B0('P2-SYNC-15', 'hub.sync.state starts "pending"; Home, the TV and the kids\' cards show skeletons until each card\'s channel has pulled (hub.isLoaded), offline included. e11: state "pending", no false offline line; v-initial-offline-2: Larder never paints the offline line on a warm open; Home cold load shows skeletons, then the data with 0 skeletons once the pull lands (channels now pull in parallel).', ['p2/SYNC/e11-initial-offline-state.json', 'p2/SYNC/v-initial-offline-2.json', 'p2/SYNC/v-initial-offline-2-home-cold-midpull.png']),
  B0('P3-F260-05', 'Viewing the plan writes nothing: weekStart and the summary are written only on a tick or setting change (the summary is refreshed on open only for someone who already has F260 data). guest and verify-first-open-enrols-guest-1/2: opening F260 writes nothing for Grandma Jo or Mea, and the evening and behind jobs no longer list them.', ['p3/f260/guest.json', 'p3/f260/verify-first-open-enrols-guest-1.json', 'p3/f260/verify-first-open-enrols-guest-2.json']),
  B0('P3-F260-06', 'The day key is hub.today(). verify-other-timezone-1/2 and time: the London phone logs 2026-09-22, the evening job sees readToday true, DST streak and heatmap correct.', ['p3/f260/verify-other-timezone-logs-next-day-1.json', 'p3/f260/verify-other-timezone-logs-next-day-2.json', 'p3/f260/time.json']),
  B0('P3-KIDVERSE-08', 'One star per household day: dayKey is hub.today() and isoWeek is the ISO week of the household date (the same formula as the shell). verify-device-local-day-1/2 and dates: a Los Angeles phone at 22:30 on 23 Sep stores 2026-09-24 and the New York iPad then gets "already have today\'s star"; total stays 2.', ['p3/kidverse/verify-device-local-day-1.json', 'p3/kidverse/verify-device-local-day-2.json', 'p3/kidverse/dates.json']),
  B0('P3-LEFTOVERS-06', 'An inline handler right after the form calls preventDefault from the first byte and holds the entry; it is logged once the list has loaded. verify-submit-before-ready-1/2 and before-ready A: no reload, the name kept, the item lands on the server.', ['p3/leftovers/verify-submit-before-ready-reloads-1.json', 'p3/leftovers/verify-submit-before-ready-reloads-2.json', 'p3/leftovers/verify-submit-before-ready-reloads-2-A-after-tap-iphone.png']),
  B0('P3-LEFTOVERS-07', 'Household dates via hub.today() (the date box\'s value and max included). verify-other-timezone-ages-1/2 and timezone: London and Los Angeles phones write New York\'s date and show the same ages as the New York iPad (0 differing items).', ['p3/leftovers/verify-other-timezone-ages-1.json', 'p3/leftovers/verify-other-timezone-ages-2.json', 'p3/leftovers/timezone.json']),
  B0('P3-LEFTOVERS-08', 'Submit re-keys the day (hub.today()) before it reads the date box; hub.onDay moves the box at midnight. verify-midnight-first-minute-yesterday-1/2 and midnight: "Midnight popcorn" is stored 2026-09-23 and reads 0d; leftovers-midnight-tap.mjs taps 2-3 s after midnight while the box still showed the old day: both Logs get the new date.', ['p3/leftovers/verify-midnight-first-minute-yesterday-1.json', 'p3/leftovers/midnight.json', 'p3/leftovers/verify-midnight-first-minute-yesterday-1.png']),
  B0('P3-LEFTOVERS-14', 'After a Log the box resets value and max to the household day together. critic-midnight-second-log (Chromium and WebKit) and verify-2-1/2-2: both Logs save 2026-09-23, value equals max, 0 invalid events.', ['p3/leftovers/critic-midnight-second-log.json', 'p3/leftovers/verify-critic-midnight-second-log-blocked-2-1.json', 'p3/leftovers/verify-critic-midnight-second-log-blocked-2-2.json']),
  B0('P3-PRAYER-10', 'A capture-phase guard stops taps while the data is unset, and Mine/Family, Pray now, More, the nav and + are disabled until load. verify-tap-before-ready-1/2 and leads L6: no page errors in any arm (was a TypeError on D); the Family tap hits a disabled button and the page stays put.', ['p3/prayer/verify-tap-before-ready-1.json', 'p3/prayer/verify-tap-before-ready-2.json', 'p3/prayer/verify-tap-before-ready-1-A-record-before-load.png']),
  B0('P3-PRAYER-11', 'TODAY is hub.today(); daysSince, shift and the weekday use the household date; the shell\'s TV reads prayedBy with the same date. verify-other-timezone-date-1: David in Los Angeles files under 2026-09-23 and the TV shows David and Elizabeth; dates TZ: onNewYorkTodayList true. (verify-2\'s east arm then unticks a row someone else ticked: that is P3-PRAYER-05, batch 0g.)', ['p3/prayer/verify-other-timezone-date-1.json', 'p3/prayer/dates.json', 'p3/prayer/verify-other-timezone-date-1-tv.png']),
  B0('P3-VERSES-07', 'render() shows the loading card until the channels have pulled and writeSummary() is refused before it. verify-stalled-load-zero-summary-1/2 and stalled-load: "Loading…" then the real "3 to go"; never "all done" or "Nothing to train yet"; the server summary is never zeroed.', ['p3/verses/verify-stalled-load-zero-summary-1.json', 'p3/verses/stalled-load-adult.json', 'p3/verses/stalled-load-adult-iphone.png']),
  B0('P3-VERSES-09', 'Log keys, last and due use hub.today / hub.addDays / hub.daysBetween. verify-other-timezone-day-1/2/3: the London phone stores last 2026-09-22, due 2026-09-29; the New York iPad shows "streak 14 · reviewed today".', ['p3/verses/verify-other-timezone-day-1-result.json', 'p3/verses/verify-other-timezone-day-2.json', 'p3/verses/verify-other-timezone-day-3.json']),
  B0('UX-DOLLYWOOD-LIVE-3', 'The park map (template, rebuilt and exported) says "Loading…" in the Family header while the family pull is in flight, keeps Share my spot disabled "Loading…" until the person scope loads, and the pill reads "Eli · loading…". rally-guest-loading C_loading: famSync "Loading…" (was "offline — showing last known").', ['p3/dollywood-live/rally-guest-loading.json', 'p3/dollywood-live/loading-family-ipad-dark.png']),
  B0('UX-F260-5', 'Until the first pull Done is disabled "Loading your progress…" and the stat wells are skeletons. f260-loading.mjs: during a 9 s hold Done disabled, strip empty, no weeks, a forced tap POSTs nothing; after release "Acts 6", 187 of 260, Done enabled.', ['f260-loading.json', 'f260-loading-held-iphone.png', 'f260-loading-after-iphone.png']),
  B0('UX-KIDVERSE-6', 'Skeleton art plate and text lines of the loaded size until the week arrives. webtells: the cold-load jump went from 368 px to 0 px for the measured week (Done at 851, story at 1138); other weeks\' paraphrases can still move about one line.', ['p3/kidverse/webtells.json', 'kidverse-first-load-C-loading.png']),
  B0('UX-PRAYER-8', 'A loading state on both pages: "Loading your prayer list…" with skeleton stats and rows (adult) and "Getting the family list…" with skeleton cards (kid). Recaptured by the rig (prayer today-loading, kid-loading).', ['p3/prayer/slow-start-hold9s-first-paint.png', 'audits/screens-after/0b/manifest.json']),
  B0('UX-VERSES-5', 'The static page starts as the skeleton trainer card with disabled controls and "Eli · loading…" in the pill. Recaptured by the rig (verses trainer-loading).', ['verses-A-offline-loading-iphone.png', 'verses-B-kid-cold-loading-iphone.png', 'audits/screens-after/0b/manifest.json']),
  B0('VIS-LEFTOVERS-1', 'Log and Copy labels and icons and the size options are in the markup; the date box is filled before the first await; three placeholder cards while loading. Recaptured by the rig (leftovers main-loading).', ['p3/leftovers/before-ready-B-stalled-7s-iphone.png', 'audits/screens-after/0b/manifest.json']),
  B0('P3-DOLLYWOOD-01', 'Pointer to P2-SYNC-03 (async migrate); the template now migrates only after the first load, re-reads everything on the migrated event, and moves off a step the migration has just ticked (test-dollywood-sync caught the build guide left on it, where Mark done would untick it). verify-migrate-race-progress-1 A-E and -2 C/H5/H7/F: overwritten false, server 24 kept; dollywood-first-load: an empty server row still receives the legacy tick (1 of 9) with no reload. (The shell does not add the build guide\'s channel after all: the app waits for its own pull, and the extra request every 30 s on every device bought nothing.)', ['p3/dollywood/verify-migrate-race-overwrites-progress-1.json', 'p3/dollywood/verify-migrate-race-overwrites-progress-2.json', 'dollywood-first-load.json']),
  B0('P3-TALLY-03', 'Pointer to P2-SYNC-03. verify-legacy-migrate-overwrites-count-1/2: hold9, fail, abort and chromium arms keep the server at 37 (was 37→5); the legacy key stays on the device.', ['p3/tally/verify-legacy-migrate-overwrites-count-1.json', 'p3/tally/first-load.json']),
  B0('P2-STAB-04', 'Pointer to P2-HOME-02 (Home reads the log for today).', ['p2/HOME/verify-stale-1.json']),
  B0('GAP-TELL-1', 'hub.isLoaded() / hub.loaded() give every app the "pulled" signal, and the eight apps in this batch, Home and the TV use it for skeleton or loading states. The shared loading component itself (CONS-MOTION-4) is batch 1.', ['p3/prayer/slow-start-hold9s-first-paint.png', 'tally-loading-hold-light.png']),
  B0('P2-HOME-04', 'Pointer to P2-SYNC-15: Home cards (no fake 0/5 ring or fridge hint), the kids\' star cards (no ★0) and the reminders show skeletons until their channel has pulled. Recaptured: shell home-loading, home-kid-loading.', ['p2/SYNC/v-initial-offline-2-home-cold-midpull.png', 'audits/screens-after/0b-shell/manifest.json']),
  B0('P2-VIS-04', 'Pointer to P2-SYNC-15: the TV\'s verse, prayed, stars and feed panes read "Loading…" until their data has arrived, never a false "Week 1", "No one yet" or "Nothing has happened yet". Recaptured: tv board-loading.', ['p2/SYNC/v-initial-offline-2.json', 'p3/prayer/verify-other-timezone-date-1-tv.png', 'audits/screens-after/0b-shell/manifest.json']),
  B0('P3-LEFTOVERS-05', 'Pointer to P2-SYNC-15: render() waits for the first pull; offline with no cache it says so instead of claiming a saved copy. before-ready B at 7 s: no tally, no "Nothing logged yet", placeholders; then "6 in the fridge".', ['p3/leftovers/before-ready.json', 'p3/leftovers/before-ready-B-stalled-7s-iphone.png']),
  B0('UX-TALLY-2', 'Pointer to P3-TALLY-07: disabled with aria-busy and a skeleton while loading.', ['tally-loading-hold-light.png']),
  B0('UX-TIMER-9', 'Pointer to P3-TIMER-01: a skeleton dial and a disabled "Loading…" Start instead of a fake 5:00.', ['timer-stale-taps-cold-loading.png']),
];

// Batch 0c after-evidence lives under audits/evidence/p6/0c/ (the Phase 2/3 scripts' outputs keep their p2/…, p3/… paths
// inside it; the batch's own checks, audits/tools/phase6/0c/, write straight into it). E0c = that folder.
const E0c = 'audits/evidence/p6/0c/';
const C0 = (id, note, after, status = 'FIXED') => [id, { status, batch: '0c', note, after: after.map(p => p.startsWith('audits/') ? p : E0c + p) }];
const S0c = [
  C0('P2-PROF-02', 'Every queue belongs to its writer (hub.queue.<app>.<scope>.<pid>); Switch keeps the person\'s token in hub.retiring and sends their queues with it (at once if online, else on reconnect or before the next sign-in), then logs it out; a queue that still cannot go waits for their next sign-in here. stranded-after-switch-2: with Ezra signed in 35 s later the server has Eli\'s two F260 ticks and his Forest theme (was unset / false), the iPad holds no queue, and Eli\'s phone offers 38-4 (was 38-2); the flaky arm lands Frost. switch-flush A: a reminder, an F260 row, a Tally tap and a feed line made offline all reach the server under Eli\'s token after the TV signs in.', ['p2/PROF/verify2-stranded.json', 'p2/PROF/verify2-stranded-2-eli-phone-f260.png', 'switch-flush.json']),
  C0('P2-PROF-14', 'The Worker stores no updated_at more than 30 s ahead of its clock (worker/src/data.js MAX_AHEAD_MS); hub.js keeps the last server skew (hub.skew in localStorage) so an offline write on a wrong clock is stamped in server time, adopts the server\'s stamp after a flush, and lets the server row win over a cached stamp ahead of the server; Me warns when the clock is over 5 min out. prof-14-fastclock (the Phase 2 script, family-queue reads updated to the new keys; phone 10 min fast): Dad\'s offline tap lands 2.4 s behind server now (was +299.9 s), his phone then shows "Prayed today: Kiara" (was stuck on David), his update note keeps Kiara\'s tap (server ["Kiara"], was reverted to ["David"]), and in chain K his phone reads Week 41 with Mom (was stuck on 38). The same script on the unchanged code reproduced both halves again.', ['verify4-p2-prof-14-2.json', 'verify4-p2-prof-14-2-P-fast-dad-iphone-after-10min-1x.png', 'verify4-p2-prof-14-2-P-fast-kid-ipad-after-dad-update-1x.png']),
  C0('P2-PROF-19', '"Forget this device" is shown to household adults only; it sends everything first and refuses while anything is still waiting ("Not forgotten: 2 changes not yet saved …"). forget-device A/C: offline with two queued writes it refuses and keeps both queues and the pairing; online it sends both rows first; Ezra and the display have no button, Mom has it. (The Phase 2 script stops earlier, at batch 0b\'s load guard, as it did before this batch.)', ['forget-device.json', 'forget-device-A-offline-refused.png']),
  C0('P2-SYNC-06', 'flush() sends at most 200 rows a request and loops; only a row the Worker refuses as a row (bad_key, value_too_large) is dropped, alone, with a toast; Prayer\'s import reports the house\'s answer. batch-over-200-1/2: 201 rows offline, online, and the 250-prayer import all reach the server (201/201 rows, was 0; the import 19 → 250 prayers, was 19 → 19) in requests of 200 + 1 (the import 200 + 75); switch-flush B: a bad row next to a good one drops only itself, with "1 change could not be saved to the house".', ['p2/SYNC/verify-batch-over-200-dropped-1.json', 'p2/SYNC/verify-batch-over-200-dropped-2.json', 'p2/SYNC/verify-batch-200-2-phone-prayer-after-import.png', 'switch-flush.json']),
  C0('P2-SYNC-07', 'Family queues carry the writer\'s id, so the display has no queue to send or empty; the adult\'s queue goes with the adult\'s token when the TV signs in. kiosk-drops-family-queue-2 A-tv: the reminder is on the server (was false; 0 batches with the TV\'s token, was a 403 that emptied the queue).', ['p2/SYNC/verify-kiosk-drops-family-queue-2.json', 'p2/SYNC/v2-kiosk-queue-tv-reminders-pane.png']),
  C0('P2-SYNC-09', 'hub.reset() bumps a generation, aborts every request in flight and clears the pull promise; a pull answer for a previous generation or token is discarded. cross-profile-cache-1: Ezra\'s timer cache holds only his own row (was Eli\'s timer.active, with Eli\'s timer pill on Ezra\'s Home); e6-switch-race: no foreign timer in either arm.', ['p2/SYNC/verify-switch-race-cross-profile-cache-1.json', 'p2/SYNC/verify-switch-race-cross-profile-cache-1-timer-ipad.png', 'p2/SYNC/e6-switch-race.json']),
  C0('P2-SYNC-18', 'refreshScope emits a change for every key whose value another window changed. verify2-refreshscope-2: race "ok" ×7 (was "STALE" ×7). The b2probe\'s lost tick is the whole-map race P2-SYNC-01 (batch 0e); here the phone\'s store and screen agree.', ['p2/SYNC/verify2-refreshscope-race.json']),
  C0('P3-TALLY-05', 'The shell\'s flush sends every queue of the person found on the device, not only the channels it syncs, and every page hands its queue to a keepalive request on pagehide. critic-stranded S: 35 s after reconnecting with Tally closed the server has 41 (was 37), no queue left, and the other device\'s count ends at 43 as expected; critic-stranded-online and verify-critic-stranded-queue-on-close-1-1 A/B deliver every tap.', ['p3/tally/critic-stranded.json', 'p3/tally/critic-stranded-online.json', 'p3/tally/verify-critic-stranded-queue-on-close-1-1.json']),
  C0('P2-SYNC-04', 'hub.ready() re-arms the 30 s poll every time (hub.reset() stops it). poll-dies-1: in the 65 s after the switch the iPad made 20 data GETs and the TV 22 (was 0 and 0), and both show the reminder Eli added from another device; switch-flush C: the TV made 11 data GETs in 35 s.', ['p2/SYNC/verify1-poll-dies-after-profile-switch.json', 'p2/SYNC/verify1-tv-board-65s-after-switch.png']),
  C0('P2-PROF-13', 'New POST /api/device/forget (household adults): deletes the device, its sessions and its push subscriptions; Forget calls it after everything has been sent, then clears local storage. forget-device B: the old device token gets 401 device_not_paired, the old session 401, the admin list no longer has the device, Eli has no push subscription left. (The Phase 2 script runs Forget as Ezra, who no longer has the button.)', ['forget-device.json', 'forget-device-B-online-forgotten.png']),
  C0('P2-PWA-06', 'Feed lines wait in hub.aqueue.<author>, stamped with the time they happened, and only the author\'s session posts them (a signed-out author\'s go before the logout); the Worker files them at that time (clamped to a week back, never ahead). offline-activity-misattributed-2: Eli\'s offline line posted as eli (was kiara), before Grandma Jo\'s later line.', ['p2/PWA/verify-offline-activity-misattributed-2.json', 'p2/PWA/verify-offline-activity-misattributed-2-feed-ipad-portrait-light.png']),
  C0('GAP-SYNC-a1', 'hub.persistStorage() (navigator.storage.persist) after pairing, and once on devices paired before; Me → Sync tells an iPhone or iPad Safari tab to add the hub to the Home Screen. Recaptured: shell me screens on iphone-safari.', ['me-sync-typical-iphone-safari-light.png', 'audits/screens-after/0c/manifest.json']),
  C0('P2-PROF-15', 'Switch removes the person\'s person-scope caches from the device at once (their queue stays, under their id, until sent). switch-leaves-private-caches-2: Eli\'s person keys after Switch [] (was 5 caches, 19 private prayer rows); switch-flush A: none left.', ['p2/PROF/verify-switch-leaves-private-caches-2.json', 'p2/PROF/verify2-switch-caches-ezra-prayer-ipad.png']),
  C0('P2-PWA-13', 'One drain at a time per window, and a claim on the author\'s queue shared with the other window; each line is removed by id once posted. double-post-1: the Kid Verse star posts "read the verse ★" once (was twice); switch-flush D: three overlapping calls post three lines, once each.', ['p2/PWA/verify-double-post-activity-1.json', 'p2/PWA/verify-double-post-activity-1-kidverse-feed-ipad-portrait-light.png']),
  C0('P2-PWA-14', 'On a 401 the line stays queued under its author and posts at their next sign-in here. activity-dropped-on-401-1: after the admin\'s Reset PIN and Mom\'s new PIN the feed has "Added a reminder: V401 S3 fix the gate" by mom (was missing for good).', ['p2/PWA/verify-activity-dropped-on-401-1.json']),
  C0('P2-SEC-03', 'A Switch made offline keeps the token in hub.retiring and sends the logout on reconnect (after that person\'s queue). sec-03-1 B3/B5: "POST /api/logout [old token]" on reconnect and the old token then gets 401 (was 200 for read and write); sec-03-2 S3: 401 after the online event, 1 logout. The narrower server rule the plan offered ("refused once a new session exists for that device") was not added: smoke-api.sh and the capture rig use several sessions on one device (06-implementation).', ['p2/SEC/verify4-p2-sec-03-1.json', 'p2/SEC/verify4-p2-sec-03-2.json', 'p2/SEC/session-verify3.json']),
  C0('P2-SYNC-11', 'A 401 signs out only when the failing request carried the current token (device or profile). switch-race-bounces-1: with Eli\'s request held 4 s, Ezra stays signed in and no 401 reaches him (was bounced to the picker).', ['p2/SYNC/verify-switch-race-bounces-next-person-1.json', 'p2/SYNC/verify-switch-race-1-delay4000.png']),
  C0('P2-SYNC-16', 'lsSet reports a full device; other people\'s caches and the feed copy go first; a queue that still cannot be stored stays in memory, is sent, and a toast says so; while it is memory-only the stored cache keeps the previous value, so a reload never shows an unsent change as saved. quota-errors-2: online-full and offline-stay reach the server (offline-stay was lost); after an offline reload device and server agree (the slack arm used to show a tick the server never got).', ['p2/SYNC/verify-quota-errors-swallowed-2.json']),
  C0('UX-PROF-a6', 'The theme follows the person: the picker is the device look (System), each sign-in applies that person\'s own theme (their device mirror or cached row), the sync counters start fresh, and Switch lands the next person on Home. switch-theme: picker, Ezra in flight and Kiara all hearth/system (were forest/forest/midnight); switch-flush C: Ezra lands on Home after a Switch from Me.', ['p2/PROF/switch-theme-ezra-inherits-forest.png', 'p2/PROF/switch-theme-ezra-after-pull.png', 'switch-flush-C-ezra-home.png']),
  C0('P2-PROF-01', 'Pointer to P2-SYNC-07: the display never holds or empties another person\'s family queue.', ['p2/SYNC/verify-kiosk-drops-family-queue-2.json']),
  C0('P2-PROF-03', 'Pointer to P2-SYNC-04: the poll is re-armed on every sign-in.', ['p2/SYNC/verify1-poll-dies-after-profile-switch.json']),
  C0('P2-STAB-02', 'Pointer to P2-SYNC-04.', ['p2/SYNC/verify1-poll-dies-after-profile-switch.json']),
  C0('P2-PROF-07', 'Pointer to P2-PWA-06: the per-author feed queue.', ['p2/PWA/verify-offline-activity-misattributed-2.json']),
  C0('P2-SYNC-08', 'Pointer to P2-PWA-06: lines drain on reconnect, after a pull and on sign-in, under their author.', ['p2/PWA/verify-offline-activity-misattributed-2.json']),
];

export const STATUS = {
  'P2-STAB-01': {
    status: 'FIXED', batch: '0a',
    note: 'hub.js defines hub.sheenFrom before its reduced-motion return (apps/hub.js:442); index.html:662 calls it only if it is a function. With Reduce Motion on, all 11 skeptic cases and all 6 STAB cases boot (shell or gate shown, 0 page errors) in WebKit and Chromium, and the render matches Reduce Motion off (4 pairs, 0 pixels over tolerance).',
    after: ['audits/evidence/p6/0a/VIS/verify-rm2.json', 'audits/evidence/p6/0a/STAB/reduced-motion.json', 'audits/evidence/p6/0a/VIS/verify-rm2-webkit-iphone-eli-reduce.png', 'audits/evidence/p6/0a/VIS/verify-rm2-webkit-ipad-unpaired-reduce.png'],
  },
  'P2-VIS-01': {
    status: 'FIXED', batch: '0a',
    note: 'Pointer to P2-STAB-01; its own check (density-motion.mjs, last block) now prints shellHidden=false under reduce.',
    after: ['audits/evidence/p6/0a/VIS/density-motion.json', 'audits/evidence/p6/0a/VIS/reduced-motion-reduce-webkit-ipad.png'],
  },
};

for (const [id, s] of S0b) STATUS[id] = s;
for (const [id, s] of S0c) STATUS[id] = s;

for (const [id, s] of Object.entries(STATUS)) {
  if (!STATUSES.includes(s.status)) throw new Error(`${id}: unknown status ${s.status}`);
  if (!BATCHES[s.batch]) throw new Error(`${id}: batch ${s.batch} has no BATCHES entry`);
}
