// Phase 6: the status of every finding a batch has closed, read by audits/tools/phase5/build-findings.mjs so that
// audits/05-findings.md carries it (constitution, Phase 6: "Update audits/05-findings.md with status (FIXED / PARTIAL /
// DEFERRED / NEEDS DEVICE CHECK) and the commit hash"). One entry per finding; a pointer gets its primary's status.
// The batch's full record (reruns, captures, tests, what was not verified) is in audits/06-implementation.md.
//
// BATCHES[n]: the batch's code commit and date.
// STATUS[id]: { status, batch, note, after: [after-evidence paths] }. The commit comes from the batch.

export const STATUSES = ['FIXED', 'PARTIAL', 'DEFERRED', 'NEEDS DEVICE CHECK'];

export const BATCHES = {
  '0a': { commit: 'ae274a6', date: '2026-09-26' },
  '0b': { commit: 'd968db8', date: '2026-09-26' },
};

// Batch 0b after-evidence lives under audits/evidence/p6/0b/ (the Phase 2/3 scripts' outputs, moved there from p2/p3 so the
// baseline stays as it was, plus the new checks in audits/tools/phase6/0b/). E = that folder.
const E = 'audits/evidence/p6/0b/';
const B0 = (id, note, after, status = 'FIXED') => [id, { status, batch: '0b', note, after: after.map(p => p.startsWith('audits/') ? p : E + p) }];
const S0b = [
  B0('P2-SYNC-02', 'hub.ready waits on the app\'s own channels (hub.isLoaded) and hub.set refuses an unloaded channel; Prayer loads, saves and migrates only after its person and family channels have pulled. Ezra\'s first open: server rows CHANGED {} (was prayerDays 29→0, plans replaced); family keys POSTed on first open [].', ['p2/SYNC/verify-ready-seen-ezra-real.json', 'p2/SYNC/e8-ready-seen.json']),
  B0('P2-SYNC-03', 'hub.migrate is async: it waits for the scope to load and a fresh successful pull, then writes only keys the server lacks, never for guests. e2h: server done 187 / week 38 kept, migrated mark set; verify-1 arms A-G all "overwritten = false" (failed-pull arms stay on the loading state and migrate nothing).', ['p2/SYNC/e2h-migrate-race.json', 'p2/SYNC/verify-migrate-race-overwrites-history-1.json']),
  B0('P2-SYNC-05', 'F260 writes weekStart only when a week really starts (first tick or setCurrent), never on open. e2d: no POSTs during the held pull, weekStart 38 weeks kept; verify-2: all five variants "intact".', ['p2/SYNC/e2d-slow-first-pull.json', 'p2/SYNC/verify2-slow-first-pull.json', 'p2/SYNC/e2d-phone-f260-at-7s.png']),
  B0('P2-SYNC-17', 'Done is disabled "Loading your progress…" until the f260 channel has pulled. critic-done-during-stall: at 7 s Done read "Loading your progress…", the tap landed after the data: done 187→188, log 169→170 (was wiped). verify2-2 A-D all 188/170, weekStart intact; verify2-1\'s stall arm now times out on the disabled Done (the fix holding), and f260-loading.mjs shows a forced tap during the hold POSTs nothing.', ['p2/SYNC/critic-done-during-stall.json', 'p2/SYNC/verify2-done-during-stalled-pull-2.json', 'f260-loading.json', 'f260-loading-held-iphone.png']),
  B0('P3-KIDVERSE-01', 'Done ★ is disabled "Getting your stars…" until both kidverse scopes have pulled; award() and reconcile() run only when loaded. verify-award-1/2: slow, fail, outage, latency and blip arms leave total/earned/badges/payouts intact and add exactly one star after load; kidverse-first-load A: direct award() returns false with 0 POSTs.', ['p3/kidverse/verify-award-first-pull-wipes-stars-1.json', 'p3/kidverse/verify-award-first-pull-wipes-stars-2.json', 'kidverse-first-load-A-outage.png', 'kidverse-first-load-A-after.png']),
  B0('P3-KIDVERSE-03', 'The adult week stepper is disabled ("Loading the family week…") until the family scope has pulled. verify-week-stepper-1: the tap stepped the real week 38→39, not 1→2; -2\'s fail arm now times out on the disabled + (the fix holding); kidverse-first-load B: setWeek(2) sends 0 POSTs, server keeps week 38.', ['p3/kidverse/verify-week-stepper-stalled-overwrite-1.json', 'p3/kidverse/adult-week.json', 'kidverse-first-load-B-outage.png']),
  B0('P3-KIDVERSE-11', '"I heard it" is disabled "Getting your story…" until the story rows have pulled. All three heard scripts: earlier heard days survive ("Heard 2 days this week").', ['p3/kidverse/critic-heard-first2.json', 'p3/kidverse/verify-critic-heard-first-load-overwrites-story-row-3-1.json', 'p3/kidverse/verify-critic-heard-first-load-overwrites-story-row-3-2.json']),
  B0('P3-PRAYER-02', 'Prayer paints a loading state and writes nothing until its channels have pulled. slow-start hold9s: first paint "Loading your prayer list…", posts [], prayerDays 41 and plans unchanged (was 8+6 keys POSTed, 41→0); verify-1/2 latency, fail503, hold9s and network-error arms: no wipe.', ['p3/prayer/slow-start.json', 'p3/prayer/verify-slow-start-person-wipe-1.json', 'p3/prayer/verify-slow-start-person-wipe-2.json', 'p3/prayer/slow-start-hold9s-first-paint.png']),
  B0('P3-TALLY-02', '+, − and Reset are disabled (aria-busy) until the count has arrived. first-load hold/fail: shownAtReady "", the tap lands after load on the real count 37→38 (was 37→1); kid 12→13; tally-loading.mjs: forced taps at 2 s change nothing and send nothing.', ['p3/tally/first-load.json', 'p3/tally/verify-first-load-tap-overwrites-count-2.json', 'tally-loading-hold-light.png', 'tally-loading-fail-dark.png']),
  B0('P3-VERSES-03', 'No rating until the verses and f260 channels (and kidverse family for kids) have pulled: Show and the ratings are disabled on a skeleton card. verify-first-open-1 slow/control and -2 latency: server log 13→14 days (was cut to 1); the offline and kid arms now time out on the disabled Show (the fix holding); verses-first-open.mjs A/B: offline and cold-kid taps queue nothing.', ['p3/verses/verify-first-open-wipes-log-1-slow-result.json', 'p3/verses/verify-first-open-wipes-log-2-latency.json', 'verses-A-offline-loading-iphone.png', 'verses-B-kid-cold-loading-iphone.png']),
  B0('P2-HOME-02', 'F260\'s summary carries readOn; Home computes "read today" and the streak from the synced f260.log for today\'s New York date (F260\'s own streak rule), chat\'s f260_status reads the log too, and the 8 pm job already did. verify-stale-1: Tue "reading done · read today ✓"; Wed "a reading waiting" (was "reading done"); Sat, 3 unread days later, no streak.', ['p2/HOME/verify-stale-1.json', 'p2/HOME/verify-stale-2.json']),
  B0('P2-STAB-07', 'F260 and Kid Verse re-render on hub.onDay (and on visibility when the day changed); the shell re-renders Home at the household midnight. midnight.mjs: F260 rolls to "TODAY / Mon, Sep 28"; Kid Verse drops last week\'s stars and rings Monday; the kid Home card goes from 3 stars to "No stars yet".', ['p2/STAB/midnight.json', 'p2/STAB/midnight-tue.json']),
  B0('P3-LEFTOVERS-03', 'Ages are hub.daysBetween(dateLogged, hub.today()) in the Larder and on Home. verify-dst-1/2 and dates: ages equal calendar days across spring-forward and fall-back.', ['p3/leftovers/verify-dst-spring-forward-off-by-one-1.json', 'p3/leftovers/verify-dst-spring-forward-off-by-one-2.json', 'p3/leftovers/dates-dst.json']),
  B0('P3-TALLY-06', 'hub.profile.isGuest now reaches the SDK and hub.migrate skips guests without marking the scope. critic-guest-migrate: the guest sees 0, no mark, no server row; Mom then gets 23.', ['p3/tally/critic-guest-migrate.json', 'p3/tally/verify-critic-guest-gets-legacy-migration-2-2.json']),
  B0('P3-TALLY-07', 'A skeleton pill replaces the markup\'s placeholder 0 until the count arrives. fake-zero-5-1/5-2: in every hold, fail and abort sample the dial is empty with + disabled and aria-busy, then the real 37; no 0 is ever painted.', ['p3/tally/verify-critic-fake-zero-while-loading-5-1.json', 'p3/tally/verify-critic-fake-zero-while-loading-5-2.json', 'tally-loading-hold-light.png']),
  B0('P3-TIMER-01', 'Start, Reset and the presets stay disabled on a skeleton dial until this page\'s own timer pull has succeeded, the device is truly offline with a pulled cache, or the server has been unreachable for 8 s with a pulled cache. verify-slowload-1: hold9, lat8, fail and ctrl all replaced:false; timer-stale-taps: forced taps change nothing in the warm, cold and fail arms, and offline with a warm cache Start works and queues timer.active.', ['p3/timer/verify-slowload-start-replaces-running-timer-1.json', 'timer-stale-taps-warm-loading.png', 'timer-stale-taps-offwarm-started.png']),
  B0('P3-VERSES-04', 'Verses re-renders on hub.onDay. midnight and verify-midnight-1/2: at 00:05 Eli goes from "All done for today" to "9 to go" and Ezra from "Come back tomorrow!" to "2 to go".', ['p3/verses/midnight.json', 'p3/verses/verify-midnight-stale-all-done-1.json', 'p3/verses/midnight-eli-ipad-after.png']),
  B0('UX-DOLLYWOOD-5', 'The build guide (template, rebuilt and exported) shows "Loading your progress…", chips without counts and a disabled Mark done / Next unfinished until the person scope has pulled. data-checks L1: during load "Loading your progress…", markDone.disabled true; after load "7 of 9 done"; L2: a tick during load changes nothing (server stays 24).', ['p3/dollywood/data-checks-L1-L2.json', 'p3/dollywood/first-open-loading.png']),
  B0('P2-SYNC-15', 'hub.sync.state starts "pending"; Home, the TV and the kids\' cards show skeletons until each card\'s channel has pulled (hub.isLoaded), offline included. e11: state "pending", no false offline line; v-initial-offline-2: Larder never paints the offline line on a warm open; Home cold load shows skeletons, then the data with 0 skeletons once the pull lands (channels now pull in parallel).', ['p2/SYNC/e11-initial-offline-state.json', 'p2/SYNC/v-initial-offline-2.json', 'p2/SYNC/v-initial-offline-2-home-cold-midpull.png']),
  B0('P3-F260-05', 'Viewing the plan writes nothing: weekStart and the summary are written only on a tick or setting change (the summary is refreshed on open only for someone who already has F260 data). guest and verify-first-open-enrols-guest-1/2: opening F260 writes nothing for Grandma Jo or Mea, and the evening and behind jobs no longer list them.', ['p3/f260/guest.json', 'p3/f260/verify-first-open-enrols-guest-1.json', 'p3/f260/verify-first-open-enrols-guest-2.json']),
  B0('P3-F260-06', 'The day key is hub.today(). verify-other-timezone-1/2 and time: the London phone logs 2026-09-22, the evening job sees readToday true, DST streak and heatmap correct.', ['p3/f260/verify-other-timezone-logs-next-day-1.json', 'p3/f260/verify-other-timezone-logs-next-day-2.json', 'p3/f260/time.json']),
  B0('P3-KIDVERSE-08', 'One star per household day: dayKey is hub.today() and isoWeek is the ISO week of the household date (the same formula as the shell). verify-device-local-day-1/2 and dates: a Los Angeles phone at 22:30 on 23 Sep stores 2026-09-24 and the New York iPad then gets "already have today\'s star"; total stays 2.', ['p3/kidverse/verify-device-local-day-1.json', 'p3/kidverse/verify-device-local-day-2.json', 'p3/kidverse/dates.json']),
  B0('P3-LEFTOVERS-06', 'An inline handler right after the form calls preventDefault from the first byte and holds the entry; it is logged once the list has loaded. verify-submit-before-ready-1/2 and before-ready A: no reload, the name kept, the item lands on the server.', ['p3/leftovers/verify-submit-before-ready-reloads-1.json', 'p3/leftovers/verify-submit-before-ready-reloads-2.json', 'p3/leftovers/verify-submit-before-ready-reloads-2-A-after-tap-iphone.png']),
  B0('P3-LEFTOVERS-07', 'Household dates via hub.today() (the date box\'s value and max included). verify-other-timezone-ages-1/2 and timezone: London and Los Angeles phones write New York\'s date and show the same ages as the New York iPad (0 differing items).', ['p3/leftovers/verify-other-timezone-ages-1.json', 'p3/leftovers/verify-other-timezone-ages-2.json', 'p3/leftovers/timezone.json']),
  B0('P3-LEFTOVERS-08', 'Submit re-keys the day (hub.today()) before it reads the date box; hub.onDay moves the box at midnight. verify-midnight-first-minute-yesterday-1/2 and midnight: "Midnight popcorn" is stored 2026-09-23 and reads 0d; leftovers-midnight-tap.mjs taps 2-3 s after midnight while the box still showed the old day: both Logs get the new date.', ['p3/leftovers/verify-midnight-first-minute-yesterday-1.json', 'p3/leftovers/midnight.json', 'p3/leftovers/verify-midnight-first-minute-yesterday-1.png']),
  B0('P3-LEFTOVERS-14', 'After a Log the box resets value and max to the household day together. critic-midnight-second-log (Chromium and WebKit) and verify-2-1/2-2: both Logs save 2026-09-23, value equals max, 0 invalid events.', ['p3/leftovers/critic-midnight-second-log.json', 'p3/leftovers/verify-critic-midnight-second-log-blocked-2-1.json', 'p3/leftovers/verify-critic-midnight-second-log-blocked-2-2.json']),
  B0('P3-PRAYER-10', 'A capture-phase guard stops taps while the data is unset, and Mine/Family, Pray now, More, the nav and + are disabled until load. verify-tap-before-ready-1/2 and leads L6: no page errors in any arm (was a TypeError on D); the Family tap hits a disabled button and the page stays put.', ['p3/prayer/verify-tap-before-ready-1.json', 'p3/prayer/verify-tap-before-ready-2.json', 'p3/prayer/verify-tap-before-ready-1-A-record-before-load.png']),
  B0('P3-PRAYER-11', 'TODAY is hub.today(); daysSince, shift and the weekday use the household date; the shell\'s TV reads prayedBy with the same date. verify-other-timezone-date-1: David in Los Angeles files under 2026-09-23 and the TV shows David and Elizabeth; dates TZ: onNewYorkTodayList true. (verify-2\'s east arm then unticks a row someone else ticked: that is P3-PRAYER-05, batch 0g.)', ['p3/prayer/verify-other-timezone-date-1.json', 'p3/prayer/dates.json', 'p3/prayer/verify-other-timezone-date-1-tv.png']),
  B0('P3-VERSES-07', 'render() shows the loading card until the channels have pulled and writeSummary() is refused before it. verify-stalled-load-zero-summary-1/2 and stalled-load: "Loading…" then the real "3 to go"; never "all done" or "Nothing to train yet"; the server summary is never zeroed.', ['p3/verses/verify-stalled-load-zero-summary-1.json', 'p3/verses/stalled-load-adult.json', 'p3/verses/stalled-load-adult-iphone.png']),
  B0('P3-VERSES-09', 'Log keys, last and due use hub.today / hub.addDays / hub.daysBetween. verify-other-timezone-day-1/2/3: the London phone stores last 2026-09-22, due 2026-09-29; the New York iPad shows "streak 14 · reviewed today".', ['p3/verses/verify-other-timezone-day-1-result.json', 'p3/verses/verify-other-timezone-day-2.json', 'p3/verses/verify-other-timezone-day-3.json']),
  B0('UX-DOLLYWOOD-LIVE-3', 'The park map (template, rebuilt and exported) says "Loading…" in the Family header while the family pull is in flight, keeps Share my spot disabled "Loading…" until the person scope loads, and the pill reads "Eli · loading…". rally-guest-loading C_loading: famSync "Loading…" (was "offline — showing last known").', ['p3/dollywood-live/rally-guest-loading.json', 'p3/dollywood-live/loading-family-ipad-dark.png']),
  B0('UX-F260-5', 'Until the first pull Done is disabled "Loading your progress…" and the stat wells are skeletons. f260-loading.mjs: during a 9 s hold Done disabled, strip empty, no weeks, a forced tap POSTs nothing; after release "Acts 6", 187 of 260, Done enabled.', ['f260-loading.json', 'f260-loading-held-iphone.png', 'f260-loading-after-iphone.png']),
  B0('UX-KIDVERSE-6', 'Skeleton art plate and text lines of the loaded size until the week arrives. webtells: the cold-load jump went from 368 px to 0 px for the measured week (Done at 851, story at 1138); other weeks\' paraphrases can still move about one line.', ['p3/kidverse/webtells.json', 'kidverse-first-load-C-loading.png']),
  B0('UX-PRAYER-8', 'A loading state on both pages: "Loading your prayer list…" with skeleton stats and rows (adult) and "Getting the family list…" with skeleton cards (kid). Recaptured by the rig (prayer today-loading, kid-loading).', ['p3/prayer/slow-start-hold9s-first-paint.png', 'audits/screens-after/0b/manifest.json']),
  B0('UX-VERSES-5', 'The static page starts as the skeleton trainer card with disabled controls and "Eli · loading…" in the pill. Recaptured by the rig (verses trainer-loading).', ['verses-A-offline-loading-iphone.png', 'verses-B-kid-cold-loading-iphone.png', 'audits/screens-after/0b/manifest.json']),
  B0('VIS-LEFTOVERS-1', 'Log and Copy labels and icons and the size options are in the markup; the date box is filled before the first await; three placeholder cards while loading. Recaptured by the rig (leftovers main-loading).', ['p3/leftovers/before-ready-B-stalled-7s-iphone.png', 'audits/screens-after/0b/manifest.json']),
  B0('P3-DOLLYWOOD-01', 'Pointer to P2-SYNC-03 (async migrate); the template now migrates only after the first load, re-reads everything on the migrated event, and moves off a step the migration has just ticked (test-dollywood-sync caught the build guide left on it, where Mark done would untick it). verify-migrate-race-progress-1 A-E and -2 C/H5/H7/F: overwritten false, server 24 kept; dollywood-first-load: an empty server row still receives the legacy tick (1 of 9) with no reload. (The shell does not add the build guide\'s channel after all: the app waits for its own pull, and the extra request every 30 s on every device bought nothing.)', ['p3/dollywood/verify-migrate-race-overwrites-progress-1.json', 'p3/dollywood/verify-migrate-race-overwrites-progress-2.json', 'dollywood-first-load.json']),
  B0('P3-TALLY-03', 'Pointer to P2-SYNC-03. verify-legacy-migrate-overwrites-count-1/2: hold9, fail, abort and chromium arms keep the server at 37 (was 37→5); the legacy key stays on the device.', ['p3/tally/verify-legacy-migrate-overwrites-count-1.json', 'p3/tally/first-load.json']),
  B0('P2-STAB-04', 'Pointer to P2-HOME-02 (Home reads the log for today).', ['p2/HOME/verify-stale-1.json']),
  B0('GAP-TELL-1', 'hub.isLoaded() / hub.loaded() give every app the "pulled" signal, and the eight apps in this batch, Home and the TV use it for skeleton or loading states. The shared loading component itself (CONS-MOTION-4) is batch 1.', ['p3/prayer/slow-start-hold9s-first-paint.png', 'tally-loading-hold-light.png']),
  B0('P2-HOME-04', 'Pointer to P2-SYNC-15: Home cards (no fake 0/5 ring or fridge hint), the kids\' star cards (no ★0) and the reminders show skeletons until their channel has pulled. Recaptured: shell home-loading, home-kid-loading.', ['p2/SYNC/v-initial-offline-2-home-cold-midpull.png', 'audits/screens-after/0b-shell/manifest.json']),
  B0('P2-VIS-04', 'Pointer to P2-SYNC-15: the TV\'s verse, prayed, stars and feed panes read "Loading…" until their data has arrived, never a false "Week 1", "No one yet" or "Nothing has happened yet". Recaptured: tv board-loading.', ['p2/SYNC/v-initial-offline-2.json', 'p3/prayer/verify-other-timezone-date-1-tv.png', 'audits/screens-after/0b-shell/manifest.json']),
  B0('P3-LEFTOVERS-05', 'Pointer to P2-SYNC-15: render() waits for the first pull; offline with no cache it says so instead of claiming a saved copy. before-ready B at 7 s: no tally, no "Nothing logged yet", placeholders; then "6 in the fridge".', ['p3/leftovers/before-ready.json', 'p3/leftovers/before-ready-B-stalled-7s-iphone.png']),
  B0('UX-TALLY-2', 'Pointer to P3-TALLY-07: disabled with aria-busy and a skeleton while loading.', ['tally-loading-hold-light.png']),
  B0('UX-TIMER-9', 'Pointer to P3-TIMER-01: a skeleton dial and a disabled "Loading…" Start instead of a fake 5:00.', ['timer-stale-taps-cold-loading.png']),
];

export const STATUS = {
  'P2-STAB-01': {
    status: 'FIXED', batch: '0a',
    note: 'hub.js defines hub.sheenFrom before its reduced-motion return (apps/hub.js:442); index.html:662 calls it only if it is a function. With Reduce Motion on, all 11 skeptic cases and all 6 STAB cases boot (shell or gate shown, 0 page errors) in WebKit and Chromium, and the render matches Reduce Motion off (4 pairs, 0 pixels over tolerance).',
    after: ['audits/evidence/p6/0a/VIS/verify-rm2.json', 'audits/evidence/p6/0a/STAB/reduced-motion.json', 'audits/evidence/p6/0a/VIS/verify-rm2-webkit-iphone-eli-reduce.png', 'audits/evidence/p6/0a/VIS/verify-rm2-webkit-ipad-unpaired-reduce.png'],
  },
  'P2-VIS-01': {
    status: 'FIXED', batch: '0a',
    note: 'Pointer to P2-STAB-01; its own check (density-motion.mjs, last block) now prints shellHidden=false under reduce.',
    after: ['audits/evidence/p6/0a/VIS/density-motion.json', 'audits/evidence/p6/0a/VIS/reduced-motion-reduce-webkit-ipad.png'],
  },
};

for (const [id, s] of S0b) STATUS[id] = s;

for (const [id, s] of Object.entries(STATUS)) {
  if (!STATUSES.includes(s.status)) throw new Error(`${id}: unknown status ${s.status}`);
  if (!BATCHES[s.batch]) throw new Error(`${id}: batch ${s.batch} has no BATCHES entry`);
}
