// Contact sheets and the index. For every captured screen: one JPEG grid (rows = state × mode, columns = devices)
// at audits/screens/_sheets/<area>--<screen>.jpg, then the generated index section of audits/01-capture.md
// (between the INDEX markers; the hand-written parts of that file are left alone).
import fs from 'node:fs';
import path from 'node:path';
import { DEVICES, STATES, MODES } from './devices.mjs';

const K = 0.2;   // thumbnail scale: CSS px of the device viewport → sheet px
const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

export async function buildSheets(browser, { root, out, areas = null }) {
  const manifest = JSON.parse(fs.readFileSync(path.join(out, 'manifest.json'), 'utf8'));
  const caps = manifest.captures.filter(c => !areas || areas.includes(c.area));
  const byScreen = new Map();
  for (const c of caps) { const k = c.area + '--' + c.screen; if (!byScreen.has(k)) byScreen.set(k, []); byScreen.get(k).push(c); }
  const dir = path.join(out, '_sheets');
  fs.mkdirSync(dir, { recursive: true });
  const page = await browser.newPage({ viewport: { width: 1200, height: 800 } });
  for (const [key, list] of byScreen) {
    const devices = Object.keys(DEVICES).filter(d => list.some(c => c.device === d));
    const rows = [];
    for (const st of STATES) for (const m of MODES) { const r = list.filter(c => c.state === st && c.mode === m); if (r.length) rows.push({ st, m, r }); }
    const cell = (c, d) => {
      const w = Math.round(DEVICES[d].viewport.width * K), h = Math.round(DEVICES[d].viewport.height * K);
      if (!c) return `<td><div class="none" style="width:${w}px;height:${h}px">—</div></td>`;
      const b64 = fs.readFileSync(path.join(root, c.file)).toString('base64');
      return `<td><img src="data:image/png;base64,${b64}" style="width:${w}px;height:${h}px" class="${c.ok ? '' : 'bad'}">${c.ok ? '' : '<div class="err">capture error</div>'}</td>`;
    };
    const html = `<!doctype html><meta charset="utf-8"><style>
      body{margin:0;padding:16px;font:13px/1.3 system-ui,sans-serif;background:#f2f2f7;color:#1c1c1e}
      h1{font-size:18px;margin:0 0 10px} table{border-collapse:separate;border-spacing:8px 8px}
      th{font-weight:600;text-align:left;color:#3c3c43;white-space:nowrap} td{vertical-align:top}
      img{display:block;border-radius:6px;box-shadow:0 0 0 1px rgba(0,0,0,.12)} img.bad{box-shadow:0 0 0 3px #d70015}
      .none{display:flex;align-items:center;justify-content:center;color:#aeaeb2;border:1px dashed #c7c7cc;border-radius:6px}
      .err{color:#d70015;font-weight:600} .dark th.row{color:#3c3c43}
    </style><h1>${esc(key.replace('--', ' / '))}</h1><table><tr><th></th>${devices.map(d => `<th>${esc(d)}</th>`).join('')}</tr>
    ${rows.map(({ st, m, r }) => `<tr><th class="row">${esc(st)}<br>${esc(m)}</th>${devices.map(d => cell(r.find(c => c.device === d), d)).join('')}</tr>`).join('')}</table>`;
    await page.setContent(html, { waitUntil: 'load' });
    await page.evaluate(() => Promise.all([...document.images].map(i => i.decode().catch(() => {}))));
    const box = await page.evaluate(() => { const r = document.querySelector('table').getBoundingClientRect(); return { w: Math.ceil(r.right + 16), h: Math.ceil(r.bottom + 16) }; });
    await page.setViewportSize({ width: Math.min(Math.max(box.w, 400), 4000), height: Math.min(box.h, 16000) });
    await page.screenshot({ path: path.join(dir, key + '.jpg'), clip: { x: 0, y: 0, width: Math.min(Math.max(box.w, 400), 4000), height: Math.min(box.h, 16000) }, type: 'jpeg', quality: 80 });
  }
  await page.close();
  writeIndex(root, out, manifest);
}

export function writeIndex(root, out, manifest) {
  const md = path.join(root, 'audits', '01-capture.md');
  const caps = manifest.captures;
  const areas = [...new Set(caps.map(c => c.area))];
  const lines = [];
  const bad = caps.filter(c => !c.ok);
  lines.push(`Generated by \`node audits/tools/capture.mjs\` from \`audits/screens/manifest.json\` (${caps.length} captures, ${bad.length} failed; engine ${manifest.engine}; demo time ${manifest.demoTime}; scale ${manifest.scale}).`, '');
  lines.push('| Area | Screens | Captures | Failed | Captures with console errors |', '|---|---|---|---|---|');
  for (const a of areas) {
    const c = caps.filter(x => x.area === a);
    lines.push(`| ${a} | ${new Set(c.map(x => x.screen)).size} | ${c.length} | ${c.filter(x => !x.ok).length} | ${c.filter(x => (x.console || []).some(l => /^(error|pageerror)/.test(l))).length} |`);
  }
  for (const a of areas) {
    lines.push('', `### ${a}`);
    const screens = [...new Set(caps.filter(c => c.area === a).map(c => c.screen))];
    for (const s of screens) {
      const c = caps.filter(x => x.area === a && x.screen === s);
      const states = STATES.filter(st => c.some(x => x.state === st));
      const note = c.find(x => x.note)?.note;
      lines.push('', `#### ${a} / ${s}`, '');
      if (note) lines.push(note, '');
      lines.push(`States: ${states.join(', ')} · devices: ${[...new Set(c.map(x => x.device))].join(', ')} · ${c.length} files: \`audits/screens/${a}/${s}-<state>-<device>-<mode>.png\``, '');
      lines.push(`![${a} / ${s}](screens/_sheets/${a}--${s}.jpg)`);
      const errs = c.filter(x => !x.ok);
      if (errs.length) lines.push('', 'Capture failures: ' + errs.map(x => `\`${path.basename(x.file)}\` (${x.error})`).join('; '));
      const cons = [...new Set(c.flatMap(x => (x.console || []).filter(l => /^(error|pageerror)/.test(l))))];
      if (cons.length) lines.push('', 'Console errors seen: ' + cons.slice(0, 6).map(l => '`' + l.replace(/`/g, "'").slice(0, 160) + '`').join('; '));
    }
  }
  const START = '<!-- INDEX:START (generated by audits/tools/capture.mjs — do not edit by hand) -->', END = '<!-- INDEX:END -->';
  let doc = fs.existsSync(md) ? fs.readFileSync(md, 'utf8') : `# Phase 1: visual capture\n\n## Contact-sheet index\n\n${START}\n${END}\n`;
  if (!doc.includes(START)) doc += `\n## Contact-sheet index\n\n${START}\n${END}\n`;
  doc = doc.slice(0, doc.indexOf(START) + START.length) + '\n' + lines.join('\n') + '\n' + doc.slice(doc.indexOf(END));
  fs.writeFileSync(md, doc);
}

// CLI: rebuild the contact sheets and the index from audits/screens/manifest.json without capturing again.
//   node audits/tools/lib/sheets.mjs
import { fileURLToPath } from 'node:url';
import os from 'node:os';
import { createRequire } from 'node:module';
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
  const home = process.env.HUB_AUDIT_HOME || path.join(process.env.LOCALAPPDATA || os.homedir(), 'house-hub-audit');
  process.env.PLAYWRIGHT_BROWSERS_PATH ||= path.join(home, 'browsers');
  const { webkit } = createRequire(path.join(home, 'noop.js'))('playwright-core');
  const browser = await webkit.launch();
  await buildSheets(browser, { root, out: path.join(root, 'audits', 'screens') });
  await browser.close();
  console.log('sheets and index rebuilt');
}
